using Entities.Concrete;
using Microsoft.EntityFrameworkCore;
using Repositories.Context;
namespace ConsoleUI
{
    internal class Program
    {
       

        static void Main(string[] args)
        {
            KaloriTakipDbContext context = new KaloriTakipDbContext();

            FoodCategory denizUrunu = new FoodCategory() { CategoryName = "Deniz Ürünü" };
            FoodCategory tavuk = new FoodCategory() { CategoryName = "Tavuk" };
            FoodCategory meyve = new FoodCategory() { CategoryName = "Meyve" };
            FoodCategory tatli = new FoodCategory() { CategoryName = "Tatlı" };
            FoodCategory sutVeSutUrunu = new FoodCategory() { CategoryName = "Süt ve Süt Ürünü" };
            FoodCategory kirmiziEt = new FoodCategory() { CategoryName = "Kırmızı Et" };
            FoodCategory kahvaltilik = new FoodCategory() { CategoryName = "Kahvaltılık" };
            FoodCategory tahil = new FoodCategory() { CategoryName = "Tahıl" };
            FoodCategory soslar = new FoodCategory() { CategoryName = "Soslar" };
            FoodCategory fastfood = new FoodCategory() { CategoryName = "FastFood" };
            FoodCategory sebze = new FoodCategory() { CategoryName = "Sebze" };
            FoodCategory salatalar = new FoodCategory() { CategoryName = "Salatalar" };
            FoodCategory cerez = new FoodCategory() { CategoryName = "Çerez" };
            FoodCategory corba = new FoodCategory() { CategoryName = "Çorba" };
            FoodCategory yag = new FoodCategory() { CategoryName = "Yağ" };


            Food midyeDolma = new Food() { Name = "Midye Dolma", Calorie = 26F, Carbonhidrate = 3.08F, Protein = 1.62F, Fat = 0.71F, Gram = 30, FoodCategoryId = 1 };
            Food susi = new Food() { Name = "Suşi", Calorie = 125F, Carbonhidrate = 12.42F, Protein = 3.04F, Fat = 7.15F, Gram = 155, FoodCategoryId = 1 };
            Food KizarmisKanat = new Food() { Name = "Kızarmış Tavuk Kanadı", Calorie = 69F, Carbonhidrate = 0.50F, Protein = 5.85F, Fat = 4.92F, Gram = 30, FoodCategoryId = 2 };
            Food HaslanmisBut = new Food() { Name = "Haşlanmış Tavuk But", Calorie = 117F, Carbonhidrate = 4.38F, Protein = 7.96F, Gram = 80, Fat = 7.17F, FoodCategoryId = 2 };
            Food TavukKoftesi = new Food() { Name = "Tavuk Köftesi", Calorie = 46F, Carbonhidrate = 2.25F, Protein = 4.13F, Gram = 30, Fat = 2.25F, FoodCategoryId = 2 };
            Food TavukluPilav = new Food() { Name = "Tavuklu Pilav", Calorie = 336F, Carbonhidrate = 46.77F, Protein = 15.90F, Fat = 9.03F, Gram = 220, FoodCategoryId = 2 };
            Food TavukNugget = new Food() { Name = "Tavuk Nugget", Calorie = 121F, Carbonhidrate = 2.7F, Protein = 7.2F, Fat = 9F, Gram = 45, FoodCategoryId = 2 };
            Food KoriSosluTavuk = new Food() { Name = "Ekmek Arası Tavuk Döner", Calorie = 243F, Carbonhidrate = 8.92F, Protein = 31.95F, Fat = 7.9F, Gram = 170, FoodCategoryId = 2 };
            Food TavukSote = new Food() { Name = "Tavuk Sote", Calorie = 309F, Carbonhidrate = 15.13F, Protein = 43.10F, Fat = 36.37F, Gram = 250, FoodCategoryId = 2 };
            Food Elma = new Food() { Name = "Elma", Calorie = 95F, Carbonhidrate = 25.13F, Protein = 0.47F, Fat = 0.31F, Gram = 180, FoodCategoryId = 3 };
            Food Armut = new Food() { Name = "Armut", Calorie = 101F, Carbonhidrate = 27.11F, Protein = 0.64F, Fat = 0.25F, Gram = 178, FoodCategoryId = 3 };
            Food Portakal = new Food() { Name = "Portakal", Calorie = 62F, Carbonhidrate = 15.40F, Protein = 1.25F, Fat = 0.16F, Gram = 130, FoodCategoryId = 3 };
            Food Greyfurt = new Food() { Name = "Greyfurt", Calorie = 74F, Carbonhidrate = 18.45F, Protein = 1.35F, Fat = 0.25F, Gram = 245, FoodCategoryId = 3 };
            Food Ayva = new Food() { Name = "Ayva", Calorie = 57F, Carbonhidrate = 15.30F, Protein = 0.40F, Fat = 0.10F, Gram = 250, FoodCategoryId = 3 };
            Food Mandalina = new Food() { Name = "Mandalina", Calorie = 40F, Carbonhidrate = 10.15F, Protein = 0.60F, Fat = 0.25F, Gram = 75, FoodCategoryId = 3 };
            Food Kivi = new Food() { Name = "Kivi", Calorie = 42F, Carbonhidrate = 10.10F, Protein = 0.62F, Fat = 0.25F, Gram = 69, FoodCategoryId = 3 };
            Food Muz = new Food() { Name = "Muz", Calorie = 105F, Carbonhidrate = 27F, Protein = 1.30F, Fat = 0.40F, Gram = 118, FoodCategoryId = 3 };
            Food Kayisi = new Food() { Name = "Kayısı", Calorie = 17F, Carbonhidrate = 3.90F, Protein = 0.50F, Fat = 0.15F, Gram = 35, FoodCategoryId = 3 };
            Food Cilek = new Food() { Name = "Çilek", Calorie = 46F, Carbonhidrate = 11F, Protein = 0.95F, Fat = 0.45F, Gram = 144, FoodCategoryId = 3 };
            Food TrabzonHurmasi = new Food() { Name = "Trabzon Hurması", Calorie = 60F, Carbonhidrate = 16F, Protein = 0.50F, Fat = 0.17F, Gram = 80, FoodCategoryId = 3 };
            Food Kiraz = new Food() { Name = "Kiraz", Calorie = 87F, Carbonhidrate = 22.10F, Protein = 1.45F, Fat = 0.30F, Gram = 138, FoodCategoryId = 3 };
            Food Visne = new Food() { Name = "Vişne", Calorie = 52F, Carbonhidrate = 13F, Protein = 1.03F, Fat = 0.30F, Gram = 250, FoodCategoryId = 3 };
            Food Kavun = new Food() { Name = "Kavun", Calorie = 54F, Carbonhidrate = 13.05F, Protein = 1.35F, Fat = 0.30F, Gram = 150, FoodCategoryId = 3 };
            Food Karpuz = new Food() { Name = "Karpuz", Calorie = 46F, Carbonhidrate = 15.13F, Protein = 43.10F, Fat = 36.37F, Gram = 150, FoodCategoryId = 3 };
            Food Ananas = new Food() { Name = "Ananas", Calorie = 28F, Carbonhidrate = 7.35F, Protein = 0.30F, Fat = 0.07F, Gram = 56, FoodCategoryId = 3 };
            Food Avakado = new Food() { Name = "Avakado", Calorie = 160F, Carbonhidrate = 8.5F, Protein = 2.0F, Fat = 14.7F, Gram = 100, FoodCategoryId = 3 };
            Food Mango = new Food() { Name = "Mango", Calorie = 100F, Carbonhidrate = 24.70F, Protein = 1.35F, Fat = 0.63F, Gram = 165, FoodCategoryId = 3 };
            Food Ahududu = new Food() { Name = "Ahududu", Calorie = 64F, Carbonhidrate = 14.70F, Protein = 1.5F, Fat = 0.80F, Gram = 125, FoodCategoryId = 3 };
            Food Bogurtlen = new Food() { Name = "Böğürtlen", Calorie = 62F, Carbonhidrate = 13.80F, Protein = 1.5F, Fat = 0.80F, Gram = 100, FoodCategoryId = 3 };
            Food YesilErik = new Food() { Name = "Yeşil Erik", Calorie = 76F, Carbonhidrate = 18.85F, Protein = 1.15F, Fat = 0.5F, Gram = 165, FoodCategoryId = 3 };
            Food Incir = new Food() { Name = "İncir", Calorie = 37F, Carbonhidrate = 9.35F, Protein = 0.4F, Fat = 0.15F, Gram = 50, FoodCategoryId = 3 };
            Food Dut = new Food() { Name = "Dut", Calorie = 60F, Carbonhidrate = 13.70F, Protein = 2F, Fat = 0.55F, Gram = 140, FoodCategoryId = 3 };
            Food Uzum = new Food() { Name = "Üzüm", Calorie = 104F, Carbonhidrate = 27.3F, Protein = 1.1F, Fat = 0.25F, Gram = 150, FoodCategoryId = 3 };
            Food Nar = new Food() { Name = "Nar", Calorie = 145F, Carbonhidrate = 33F, Protein = 3F, Fat = 2F, Gram = 170, FoodCategoryId = 3 };
            Food Seftali = new Food() { Name = "Şeftali", Calorie = 60F, Carbonhidrate = 14.30F, Protein = 1.36F, Fat = 0.38F, Gram = 150, FoodCategoryId = 3 };
            Food Limon = new Food() { Name = "Limon", Calorie = 17F, Carbonhidrate = 5.4F, Protein = 0.65F, Fat = 0.17F, Gram = 58, FoodCategoryId = 3 };
            Food KirmiziErik = new Food() { Name = "Kırmızı Erik", Calorie = 80F, Carbonhidrate = 21F, Protein = 1F, Fat = 0.15F, Gram = 135, FoodCategoryId = 3 };
            Food Sutlac = new Food() { Name = "Sütlaç", Calorie = 133F, Carbonhidrate = 21.9F, Protein = 4F, Fat = 3F, Gram = 115, FoodCategoryId = 4 };
            Food Kazandibi = new Food() { Name = "Kazandibi", Calorie = 294F, Carbonhidrate = 47.9F, Protein = 5.7F, Fat = 8F, Gram = 180, FoodCategoryId = 4 };
            Food Magnolia = new Food() { Name = "Magnolia", Calorie = 300F, Carbonhidrate = 50F, Protein = 3.5F, Fat = 7.2F, Gram = 125, FoodCategoryId = 4 };
            Food Tiramisu = new Food() { Name = "Tiramisu", Calorie = 380F, Carbonhidrate = 56.80F, Protein = 9.25F, Fat = 11.2F, Gram = 170, FoodCategoryId = 4 };
            Food Cheesecake = new Food() { Name = "Cheesecake", Calorie = 510F, Carbonhidrate = 62F, Protein = 9.75F, Fat = 23.47F, Gram = 150, FoodCategoryId = 4 };
            Food Gullac = new Food() { Name = "Güllaç", Calorie = 143F, Carbonhidrate = 21.7F, Protein = 2.55F, Fat = 4.83F, Gram = 110, FoodCategoryId = 4 };
            Food TavukGogsuTatli = new Food() { Name = "Tavuk Göğsü Tatlısı", Calorie = 165F, Carbonhidrate = 31.1F, Protein = 6.25F, Fat = 0.2F, Gram = 210, FoodCategoryId = 4 };
            Food Muhallebi = new Food() { Name = "Muhallebi", Calorie = 233F, Carbonhidrate = 38.18F, Protein = 4.7F, Fat = 4.60F, Gram = 150, FoodCategoryId = 4 };
            Food Puding = new Food() { Name = "Puding", Calorie = 132F, Carbonhidrate = 16.63F, Protein = 7.45F, Fat = 3.8F, Gram = 200, FoodCategoryId = 4 };
            Food Supangle = new Food() { Name = "Supangle", Calorie = 160F, Carbonhidrate = 19F, Protein = 4.52F, Fat = 6.63F, Gram = 130, FoodCategoryId = 4 };
            Food Trilece = new Food() { Name = "Trileçe", Calorie = 301F, Carbonhidrate = 39F, Protein = 12.85F, Fat = 9.25F, Gram = 185, FoodCategoryId = 4 };
            Food Hosmerim = new Food() { Name = "Höşmerim", Calorie = 343F, Carbonhidrate = 111F, Protein = 17F, Fat = 10.8F, Gram = 120, FoodCategoryId = 4 };
            Food Keskul = new Food() { Name = "Keşkül", Calorie = 273F, Carbonhidrate = 42.55F, Protein = 7.3F, Fat = 7.7F, Gram = 250, FoodCategoryId = 4 };
            Food Asure = new Food() { Name = "Aşure", Calorie = 344F, Carbonhidrate = 61.21F, Protein = 7.84F, Fat = 5.5F, Gram = 110, FoodCategoryId = 4 };
            Food Profiterol = new Food() { Name = "Profiterol", Calorie = 429F, Carbonhidrate = 55.8F, Protein = 5.8F, Fat = 19.3F, Gram = 180, FoodCategoryId = 4 };
            Food MeyveliDondurma = new Food() { Name = "Meyveli Dondurma", Calorie = 99F, Carbonhidrate = 21.05F, Protein = 0.97F, Fat = 1.02F, Gram = 75, FoodCategoryId = 4 };
            Food SutluDondurma = new Food() { Name = "Sütlü Dondurma", Calorie = 240F, Carbonhidrate = 30.75F, Protein = 9F, Fat = 9F, Gram = 150, FoodCategoryId = 4 };
            Food CikolataliDondurma = new Food() { Name = "Çikolatalı Dondurma", Calorie = 216F, Carbonhidrate = 28.2F, Protein = 3.8F, Fat = 11F, Gram = 100, FoodCategoryId = 4 };
            Food IrmikTatlisi = new Food() { Name = "Sütlü İrmik Tatlısı", Calorie = 262F, Carbonhidrate = 43.15F, Protein = 7F, Fat = 5F, Gram = 170, FoodCategoryId = 4 };
            Food IrmikHelvasi = new Food() { Name = "İrmik Helvası", Calorie = 532F, Carbonhidrate = 64.9F, Protein = 7.77F, Fat = 25.20F, Gram = 100, FoodCategoryId = 4 };
            Food UnHelvasi = new Food() { Name = "Un Helvası", Calorie = 294F, Carbonhidrate = 43.5F, Protein = 0.12F, Fat = 12.18F, Gram = 90, FoodCategoryId = 4 };
            Food Baklava = new Food() { Name = "Baklava", Calorie = 660F, Carbonhidrate = 79F, Protein = 12.36F, Fat = 34.35F, Gram = 160, FoodCategoryId = 4 };
            Food Kadayif = new Food() { Name = "Kadayıf", Calorie = 422F, Carbonhidrate = 51.75F, Protein = 6.85F, Fat = 22.55F, Gram = 145, FoodCategoryId = 4 };
            Food SogukBaklava = new Food() { Name = "Soğuk Baklava", Calorie = 242F, Carbonhidrate = 34.45F, Protein = 3.3F, Fat = 14.75F, Gram = 82, FoodCategoryId = 4 };
            Food Tulumba = new Food() { Name = "Tulumba", Calorie = 256F, Carbonhidrate = 40.7F, Protein = 2.51F, Fat = 7.25F, Gram = 90, FoodCategoryId = 4 };
            Food Kemalpasa = new Food() { Name = "Kemalpaşa", Calorie = 476F, Carbonhidrate = 84.4F, Protein = 16.6F, Fat = 13.55F, Gram = 285, FoodCategoryId = 4 };
            Food HalkaTatlisi = new Food() { Name = "Halka Tatlısı", Calorie = 673F, Carbonhidrate = 66.75F, Protein = 5F, Fat = 40.6F, Gram = 215, FoodCategoryId = 4 };
            Food SamTatlisi = new Food() { Name = "Şam Tatlısı", Calorie = 330F, Carbonhidrate = 150.75F, Protein = 18.88F, Fat = 0.94F, Gram = 90, FoodCategoryId = 4 };
            Food Sobiyet = new Food() { Name = "Şöbiyet", Calorie = 522F, Carbonhidrate = 59.76F, Protein = 5.95F, Fat = 29.15F, Gram = 160, FoodCategoryId = 4 };
            Food Kunefe = new Food() { Name = "Künefe", Calorie = 426F, Carbonhidrate = 55F, Protein = 7.36F, Fat = 20.52F, Gram = 120, FoodCategoryId = 4 };
            Food Sekerpare = new Food() { Name = "Şekerpare", Calorie = 272F, Carbonhidrate = 45.95F, Protein = 2.65F, Fat = 8.95F, Gram = 100, FoodCategoryId = 4 };
            Food Revani = new Food() { Name = "Revani", Calorie = 348F, Carbonhidrate = 55F, Protein = 5.82F, Fat = 9.4F, Gram = 100, FoodCategoryId = 4 };
            Food LokmaTatlisi = new Food() { Name = "Lokma Tatlısı", Calorie = 78F, Carbonhidrate = 7.52F, Protein = 0.35F, Fat = 4.82F, Gram = 15, FoodCategoryId = 4 };
            Food Kalburabasti = new Food() { Name = "Kalburabastı", Calorie = 251F, Carbonhidrate = 34.38F, Protein = 4F, Fat = 11.33F, Gram = 85, FoodCategoryId = 4 };
            Food FistikliSarma = new Food() { Name = "Fıstıklı Sarma Tatlısı", Calorie = 210F, Carbonhidrate = 20.95F, Protein = 3.71F, Fat = 12.08F, Gram = 50, FoodCategoryId = 4 };
            Food DilberDudagi = new Food() { Name = "Un Helvası", Calorie = 99F, Carbonhidrate = 12.63F, Protein = 0.48F, Fat = 4.81F, Gram = 30, FoodCategoryId = 4 };
            Food SanSebastian = new Food() { Name = "San Sebastian", Calorie = 480F, Carbonhidrate = 37.05F, Protein = 7.8F, Fat = 33.3F, Gram = 150, FoodCategoryId = 4 };
            Food BeyazPeynir = new Food() { Name = "Beyaz Peynir", Calorie = 93F, Carbonhidrate = 0.76F, Protein = 6.11F, Fat = 7.30F, Gram = 30, FoodCategoryId = 5 };
            Food SuzmePeynir = new Food() { Name = "Süzme Peynir", Calorie = 72F, Carbonhidrate = 1.14F, Protein = 3.4F, Fat = 6F, Gram = 30, FoodCategoryId = 5 };
            Food LorPeyniri = new Food() { Name = "Lor Peyniri", Calorie = 30F, Carbonhidrate = 0.14F, Protein = 2.17F, Fat = 2.34F, Gram = 15, FoodCategoryId = 5 };
            Food KasarPeyniri = new Food() { Name = "Kaşar Peyniri", Calorie = 71F, Carbonhidrate = 0.51F, Protein = 5.4F, Fat = 5.32F, Gram = 20, FoodCategoryId = 5 };
            Food Labne = new Food() { Name = "Labne", Calorie = 10F, Carbonhidrate = 0.28F, Protein = 0.25F, Fat = 0.9F, Gram = 5, FoodCategoryId = 5 };
            Food OrguPeynir = new Food() { Name = "Örgü Peynir", Calorie = 72F, Carbonhidrate = 0.38F, Protein = 6.25F, Fat = 5F, Gram = 25, FoodCategoryId = 5 };
            Food DilPeyniri = new Food() { Name = "Dil Peyniri", Calorie = 68F, Carbonhidrate = 1.58F, Protein = 4.3F, Fat = 4.93F, Gram = 25, FoodCategoryId = 5 };
            Food HellimPeyniri = new Food() { Name = "Hellim Peyniri", Calorie = 90F, Carbonhidrate = 0.26F, Protein = 6.98F, Fat = 7.38F, Gram = 25, FoodCategoryId = 5 };
            Food Mozarella = new Food() { Name = "Beyaz Peynir", Calorie = 90F, Carbonhidrate = 0.66F, Protein = 6.61F, Fat = 6.71F, Gram = 30, FoodCategoryId = 5 };
            Food CheddarPeyniri = new Food() { Name = "Beyaz Peynir", Calorie = 61F, Carbonhidrate = 0F, Protein = 3.71F, Fat = 5.1F, Gram = 15, FoodCategoryId = 5 };
            Food Yogurt = new Food() { Name = "Yoğurt", Calorie = 122F, Carbonhidrate = 9.32F, Protein = 6.94F, Fat = 6.5F, Gram = 200, FoodCategoryId = 5 };
            Food Cacik = new Food() { Name = "Cacık", Calorie = 115F, Carbonhidrate = 11F, Protein = 6.66F, Fat = 4.85F, Gram = 200, FoodCategoryId = 5 };
            Food HaslanmisYumurta = new Food() { Name = "Haşlanmış Yumurta", Calorie = 78F, Carbonhidrate = 0.56F, Protein = 6.3F, Fat = 5.31F, Gram = 50, FoodCategoryId = 2 };
            Food Omlet = new Food() { Name = "Omlet", Calorie = 101F, Carbonhidrate = 1.27F, Protein = 6.7F, Fat = 7.94F, Gram = 55, FoodCategoryId = 2 };
            Food PeynirliOmlet = new Food() { Name = "Peynirli Omlet", Calorie = 254F, Carbonhidrate = 2.05F, Protein = 15.3F, Fat = 15F, Gram = 130, FoodCategoryId = 2 };
            Food MantarliOmlet = new Food() { Name = "Mantarlı Omlet", Calorie = 205F, Carbonhidrate = 3.7F, Protein = 12.45F, Fat = 10F, Gram = 150, FoodCategoryId = 2 };
            Food Menemen = new Food() { Name = "Menemen", Calorie = 205F, Carbonhidrate = 3.7F, Protein = 12.45F, Fat = 10F, Gram = 150, FoodCategoryId = 2 };
            Food SucukluYumurta = new Food() { Name = "Sucuklu Yumurta", Calorie = 242F, Carbonhidrate = 3.4F, Protein = 13.5F, Fat = 19.5F, Gram = 100, FoodCategoryId = 2 };
            Food Kuymak = new Food() { Name = "Kuymak - Mıhlama", Calorie = 489F, Carbonhidrate = 3.95F, Protein = 19.1F, Fat = 44.4F, Gram = 120, FoodCategoryId = 5 };
            Food Sucuk = new Food() { Name = "Sucuk", Calorie = 166F, Carbonhidrate = 2.57F, Protein = 7.1F, Fat = 14.2F, Gram = 50, FoodCategoryId = 6 };
            Food Sosis = new Food() { Name = "Sosis", Calorie = 60F, Carbonhidrate = 0.12F, Protein = 2.24F, Fat = 5.6F, Gram = 40, FoodCategoryId = 6 };
            Food DanaSalam = new Food() { Name = "Dana Salam", Calorie = 45F, Carbonhidrate = 0.64F, Protein = 1.65F, Fat = 3.92F, Gram = 15, FoodCategoryId = 6 };
            Food HindiSalam = new Food() { Name = "Hindi Salam", Calorie = 17F, Carbonhidrate = 0.24F, Protein = 1.31F, Fat = 1.13F, Gram = 8, FoodCategoryId = 6 };
            Food DanaJambon = new Food() { Name = "Dana Jambon", Calorie = 32F, Carbonhidrate = 0.7F, Protein = 4.92F, Fat = 0F, Gram = 30, FoodCategoryId = 6 };
            Food HindiJambon = new Food() { Name = "Hindi Jambon", Calorie = 15F, Carbonhidrate = 0.35F, Protein = 2.35F, Fat = 0.46F, Gram = 12, FoodCategoryId = 2 };
            Food PilicJambon = new Food() { Name = "Piliç Jambon", Calorie = 11F, Carbonhidrate = 0.12F, Protein = 1.56F, Fat = 0.44F, Gram = 12, FoodCategoryId = 2 };
            Food HindiFume = new Food() { Name = "Hindi Füme", Calorie = 51F, Carbonhidrate = 0F, Protein = 8.8F, Fat = 1.5F, Gram = 30, FoodCategoryId = 2 };
            Food PilicFume = new Food() { Name = "Pilic Füme", Calorie = 26F, Carbonhidrate = 0.3F, Protein = 3.9F, Fat = 0.9F, Gram = 30, FoodCategoryId = 2 };
            Food Pastirma = new Food() { Name = "Pastırma", Calorie = 75F, Carbonhidrate = 0F, Protein = 8.85F, Fat = 4.17F, Gram = 30, FoodCategoryId = 6 };
            Food SiyahZeytin = new Food() { Name = "Siyah Zeytin", Calorie = 5F, Carbonhidrate = 0.24F, Protein = 0.03F, Fat = 0.44F, Gram = 4, FoodCategoryId = 3 };
            Food YesilZeytin = new Food() { Name = "Yeşil Zeytin", Calorie = 6F, Carbonhidrate = 0.15F, Protein = 0.05F, Fat = 0.61F, Gram = 4, FoodCategoryId = 3 };
            Food Bal = new Food() { Name = "Bal", Calorie = 30F, Carbonhidrate = 8.25F, Protein = 0.04F, Fat = 0F, Gram = 10, FoodCategoryId = 4 };
            Food Kaymak = new Food() { Name = "Kaymak", Calorie = 29F, Carbonhidrate = 0.17F, Protein = 0.05F, Fat = 3.16F, Gram = 5, FoodCategoryId = 5 };
            Food TahinHelvasi = new Food() { Name = "Keçi Sütü", Calorie = 197F, Carbonhidrate = 15.8F, Protein = 5.11F, Fat = 12.53F, Gram = 35, FoodCategoryId = 4 };
            Food YazHelvasi = new Food() { Name = "Cevizli Yaz Helvası", Calorie = 169F, Carbonhidrate = 13.55F, Protein = 4.41F, Fat = 10F, Gram = 30, FoodCategoryId = 4 };
            Food Tahin = new Food() { Name = "Tahin", Calorie = 87F, Carbonhidrate = 3.18F, Protein = 2.67F, Fat = 7.2F, Gram = 15, FoodCategoryId = 4 };
            Food Pekmez = new Food() { Name = "Pekmez", Calorie = 29F, Carbonhidrate = 0F, Protein = 0F, Fat = 0.01F, Gram = 10, FoodCategoryId = 4 };
            Food Nutella = new Food() { Name = "Nutella", Calorie = 27F, Carbonhidrate = 2.88F, Protein = 0.32F, Fat = 1.55F, Gram = 5, FoodCategoryId = 4 };
            Food KakaoluFindikKremasi = new Food() { Name = "Kakaolu Fındık Kreması", Calorie = 25F, Carbonhidrate = 2.71F, Protein = 0.44F, Fat = 1.38F, Gram = 5, FoodCategoryId = 4 };
            Food FindikEzmesi = new Food() { Name = "Fındık Ezmesi", Calorie = 34F, Carbonhidrate = 3.08F, Protein = 0.55F, Fat = 2.23F, Gram = 6, FoodCategoryId = 4 };
            Food FistikEzmesi = new Food() { Name = "Fıstık Ezmesi ", Calorie = 35F, Carbonhidrate = 1.3F, Protein = 1.44F, Fat = 3F, Gram = 6, FoodCategoryId = 1 };
            Food SekersizFistikEzmesi = new Food() { Name = "Şekersiz Fıstık Ezmesi", Calorie = 36F, Carbonhidrate = 1.1F, Protein = 1.32F, Fat = 2.76F, Gram = 6, FoodCategoryId = 4 };
            Food HaslanmisMakarna = new Food() { Name = "Haşlanmış Makarna", Calorie = 157F, Carbonhidrate = 30.59F, Protein = 5.8F, Fat = 0.93F, Gram = 100, FoodCategoryId = 1 };
            Food DomatesliMakarna = new Food() { Name = "Domatesli Makarna", Calorie = 178F, Carbonhidrate = 27.43F, Protein = 6.55F, Fat = 4.48F, Gram = 200, FoodCategoryId = 8 };
            Food SpagettiBolonez = new Food() { Name = "Spagetti Bolonez", Calorie = 303F, Carbonhidrate = 20.9F, Protein = 15.83F, Fat = 17F, Gram = 200, FoodCategoryId = 8 };
            Food PenneArabiata = new Food() { Name = "Penne Arabiata", Calorie = 164F, Carbonhidrate = 31.18F, Protein = 26.5F, Fat = 4.43F, Gram = 100, FoodCategoryId = 8 };
            Food Fettucini = new Food() { Name = "Fettucini Alfredo", Calorie = 289F, Carbonhidrate = 50.1F, Protein = 10.4F, Fat = 3.8F, Gram = 100, FoodCategoryId = 8 };
            Food Lazanya = new Food() { Name = "Lazanya", Calorie = 272F, Carbonhidrate = 25F, Protein = 12.65F, Fat = 13.56F, Gram = 150, FoodCategoryId = 8 };
            Food FirinMakarna = new Food() { Name = "Fırında Makarna", Calorie = 382F, Carbonhidrate = 52.26F, Protein = 17.14F, Fat = 11.2F, Gram = 230, FoodCategoryId = 8 };
            Food MakarnaSalatasi = new Food() { Name = "Makarna Salatası", Calorie = 283F, Carbonhidrate = 53.75F, Protein = 8.52F, Fat = 4.04F, Gram = 300, FoodCategoryId = 8 };
            Food Ketçap = new Food() { Name = "Ketçap", Calorie = 22F, Carbonhidrate = 4.8F, Protein = 0.25F, Fat = 0F, Gram = 20, FoodCategoryId = 9 };
            Food Mayonez = new Food() { Name = "Mayonez", Calorie = 50F, Carbonhidrate = 3.11F, Protein = 0.12F, Fat = 4.34F, Gram = 13, FoodCategoryId = 9 };
            Food Hardal = new Food() { Name = "Hardal", Calorie = 6F, Carbonhidrate = 0.58F, Protein = 0.37F, Fat = 0.33F, Gram = 8, FoodCategoryId = 9 };
            Food BarbekuSos = new Food() { Name = "Barbekü Sos", Calorie = 26F, Carbonhidrate = 6.38F, Protein = 0.12F, Fat = 0.06F, Gram = 20, FoodCategoryId = 9 };
            Food RanchSos = new Food() { Name = "Ranch Sos", Calorie = 24F, Carbonhidrate = 1.79F, Protein = 0.46F, Fat = 1.7F, Gram = 20, FoodCategoryId = 9 };
            Food BuffaloSos = new Food() { Name = "Buffalo Sos", Calorie = 56F, Carbonhidrate = 1.4F, Protein = 0.4F, Fat = 5.4F, Gram = 20, FoodCategoryId = 9 };
            Food PestoSos = new Food() { Name = "Pesto Sos", Calorie = 9F, Carbonhidrate = 0.54F, Protein = 3.47F, Fat = 4.86F, Gram = 10, FoodCategoryId = 9 };
            Food NarEkşisi = new Food() { Name = "Nar Ekşisi", Calorie = 15F, Carbonhidrate = 3.7F, Protein = 0.05F, Fat = 0F, Gram = 8, FoodCategoryId = 9 };
            Food KoriSos = new Food() { Name = "Köri Sos", Calorie = 22F, Carbonhidrate = 1.6F, Protein = 0.05F, Fat = 1.7F, Gram = 10, FoodCategoryId = 9 };
            Food SoyaSos = new Food() { Name = "Soya Sos", Calorie = 6F, Carbonhidrate = 0.56F, Protein = 1.05F, Fat = 0F, Gram = 10, FoodCategoryId = 9 };
            Food CitirTavuk = new Food() { Name = "Çıtır Tavuk", Calorie = 529F, Carbonhidrate = 38.05F, Protein = 34F, Fat = 26.65F, Gram = 200, FoodCategoryId = 2 };
            Food TavukBurger = new Food() { Name = "Tavuk Burger ", Calorie = 270F, Carbonhidrate = 33F, Protein = 13F, Fat = 10F, Gram = 100, FoodCategoryId = 10 };
            Food Cheeseburger = new Food() { Name = "Cheeseburger", Calorie = 290F, Carbonhidrate = 30.96F, Protein = 16.95F, Fat = 12F, Gram = 115, FoodCategoryId = 10 };
            Food EtliEkmek = new Food() { Name = "Etli Ekmek", Calorie = 277F, Carbonhidrate = 31.07F, Protein = 15.28F, Fat = 9.56F, Gram = 130, FoodCategoryId = 10 };
            Food Lahmacun = new Food() { Name = "Lahmacun", Calorie = 221F, Carbonhidrate = 32.27F, Protein = 9.75F, Fat = 5.55F, Gram = 150, FoodCategoryId = 10 };
            Food Tantuni = new Food() { Name = "Tantuni", Calorie = 380F, Carbonhidrate = 19.05F, Protein = 43.6F, Fat = 50.34F, Gram = 220, FoodCategoryId = 10 };
            Food PizzaKarisik = new Food() { Name = "Karışık Pizza", Calorie = 241F, Carbonhidrate = 40F, Protein = 7.8F, Fat = 5.63F, Gram = 130, FoodCategoryId = 10 };
            Food PizzaSebzeli = new Food() { Name = "Sebzeli Pizza", Calorie = 266F, Carbonhidrate = 41.23F, Protein = 13.1F, Fat = 6.6F, Gram = 220, FoodCategoryId = 10 };
            Food Kokorec = new Food() { Name = "Kokoreç Yarım Ekmek", Calorie = 433F, Carbonhidrate = 68.77F, Protein = 28.1F, Fat = 3.93F, Gram = 245, FoodCategoryId = 10 };
            Food Cigkofte = new Food() { Name = "Çiğköfte Dürüm", Calorie = 361F, Carbonhidrate = 64.75F, Protein = 15.06F, Fat = 30.64F, Gram = 150, FoodCategoryId = 10 };
            Food DurumTavukDoner = new Food() { Name = "Tavuk Döner Dürüm", Calorie = 309F, Carbonhidrate = 15.13F, Protein = 43.1F, Fat = 36.37F, Gram = 250, FoodCategoryId = 10 };
            Food DurumEtDoner = new Food() { Name = "Et Döner Dürüm", Calorie = 301F, Carbonhidrate = 19.7F, Protein = 29.65F, Fat = 45.6F, Gram = 235, FoodCategoryId = 10 };
            Food Kumpir = new Food() { Name = "Kumpir", Calorie = 1296F, Carbonhidrate = 65.74F, Protein = 50F, Fat = 92.35F, Gram = 640, FoodCategoryId = 10 };
            Food AdanaDurum = new Food() { Name = "Adana Dürüm", Calorie = 325F, Carbonhidrate = 15.02F, Protein = 27.80F, Fat = 45.5F, Gram = 200, FoodCategoryId = 10 };
            Food UrfaDurum = new Food() { Name = "Urfa Dürüm", Calorie = 325F, Carbonhidrate = 15.02F, Protein = 27.80F, Fat = 45.5F, Gram = 200, FoodCategoryId = 10 };
            Food PatatesKizartmasi = new Food() { Name = "Patates Kızartması", Calorie = 250F, Carbonhidrate = 33.15F, Protein = 2.75F, Fat = 11.8F, Gram = 80, FoodCategoryId = 10 };
            Food SoganHalkasi = new Food() { Name = "Soğan Halkası", Calorie = 97F, Carbonhidrate = 18.91F, Protein = 3.4F, Fat = 0.63F, Gram = 100, FoodCategoryId = 10 };
            Food KiymaliPide = new Food() { Name = "Kıymalı Pide", Calorie = 628F, Carbonhidrate = 73.44F, Protein = 24.6F, Fat = 25.57F, Gram = 300, FoodCategoryId = 10 };
            Food KasarliPide = new Food() { Name = "Kaşarlı Pide", Calorie = 600F, Carbonhidrate = 69F, Protein = 19.75F, Fat = 26.83F, Gram = 250, FoodCategoryId = 10 };
            Food KusbasiPide = new Food() { Name = "Kuşbaşılı pide", Calorie = 515F, Carbonhidrate = 73.2F, Protein = 28.3F, Fat = 11.5F, Gram = 350, FoodCategoryId = 10 };
            Food domates = new Food() { Name = "Domates", Calorie = 22, Carbonhidrate = 4.78F, Protein = 1.08F, Fat = 0.25F, Gram = 123, FoodCategoryId = 11 };
            Food ceriDomates = new Food() { Name = "Çeri Domates", Calorie = 27, Carbonhidrate = 5.8F, Protein = 1.31F, Fat = 0.30F, Gram = 149, FoodCategoryId = 11 };
            Food salatalik = new Food() { Name = "Salatalık", Calorie = 15, Carbonhidrate = 3.63F, Protein = 0.65F, Fat = 0.11F, Gram = 100, FoodCategoryId = 3 };
            Food marul = new Food() { Name = "Marul", Calorie = 5, Carbonhidrate = 1.03F, Protein = 0.5F, Fat = 0.05F, Gram = 36, FoodCategoryId = 11 };
            Food carlistonBiber = new Food() { Name = "Çarliston Biber", Calorie = 12, Carbonhidrate = 2.46F, Protein = 0.76F, Fat = 0.21F, Gram = 46, FoodCategoryId = 11 };
            Food kirmiziBiber = new Food() { Name = " Kırmızı Biber", Calorie = 37, Carbonhidrate = 7.18F, Protein = 1.18F, Fat = 0.36F, Gram = 119, FoodCategoryId = 11 };
            Food nane = new Food() { Name = "Nane", Calorie = 1, Carbonhidrate = 0.24F, Protein = 0.06F, Fat = 0.001F, Gram = 5, FoodCategoryId = 11 };
            Food feslegen = new Food() { Name = "Feslegen", Calorie = 1, Carbonhidrate = 0.23F, Protein = 0.13F, Fat = 0.03F, Gram = 10, FoodCategoryId = 11 };
            Food dereotu = new Food() { Name = "Dereotu", Calorie = 1, Carbonhidrate = 0.23F, Protein = 0.13F, Fat = 0.01F, Gram = 10, FoodCategoryId = 11 };
            Food kisnis = new Food() { Name = "Kişniş", Calorie = 5, Carbonhidrate = 0.99F, Protein = 0.22F, Fat = 0.32F, Gram = 5, FoodCategoryId = 11 };
            Food biberiye = new Food() { Name = "Biberiye", Calorie = 4, Carbonhidrate = 0.77F, Protein = 0.06F, Fat = 0.18F, Gram = 5, FoodCategoryId = 11 };
            Food maydanoz = new Food() { Name = "Maydanoz", Calorie = 1, Carbonhidrate = 0.24F, Protein = 0.11F, Fat = 0.03F, Gram = 5, FoodCategoryId = 11 };
            Food turp = new Food() { Name = "Turp", Calorie = 19, Carbonhidrate = 3.94F, Protein = 0.79F, Fat = 0.12F, Gram = 116, FoodCategoryId = 11 };
            Food karnabahar = new Food() { Name = "Karnabahar", Calorie = 27, Carbonhidrate = 5.32F, Protein = 2.05F, Fat = 0.3F, Gram = 107, FoodCategoryId = 11 };
            Food brokoli = new Food() { Name = "Brokoli", Calorie = 31, Carbonhidrate = 6.04F, Protein = 2.57F, Fat = 0.34F, Gram = 91, FoodCategoryId = 11 };
            Food brukselLahana = new Food() { Name = "Brüksel Lahana", Calorie = 38, Carbonhidrate = 7.88F, Protein = 2.97F, Fat = 0.26F, Gram = 88, FoodCategoryId = 11 };
            Food beyazLahana = new Food() { Name = "Beyaz Lahana", Calorie = 22, Carbonhidrate = 5.16F, Protein = 1.14F, Fat = 0.09F, Gram = 90, FoodCategoryId = 11 };
            Food kirmiziLahana = new Food() { Name = "Kırmızı Lahana", Calorie = 28, Carbonhidrate = 6.56F, Protein = 1.27F, Fat = 0.14F, Gram = 90, FoodCategoryId = 11 };
            Food havuc = new Food() { Name = "Havuc", Calorie = 25, Carbonhidrate = 5.84F, Protein = 0.57F, Fat = 0.15F, Gram = 61, FoodCategoryId = 11 };
            Food sarimsak = new Food() { Name = "Sarımsak", Calorie = 4, Carbonhidrate = 0.99F, Protein = 0.19F, Fat = 0.02F, Gram = 5, FoodCategoryId = 11 };
            Food sogan = new Food() { Name = "Soğan", Calorie = 44, Carbonhidrate = 10.27F, Protein = 1.21F, Fat = 0.11F, Gram = 110, FoodCategoryId = 11 };
            Food yesilSogan = new Food() { Name = "Yeşil Soğan", Calorie = 2, Carbonhidrate = 0.44F, Protein = 0.11F, Fat = 0.01F, Gram = 5, FoodCategoryId = 11 };
            Food semizotu = new Food() { Name = "Semizotu", Calorie = 9, Carbonhidrate = 1.46F, Protein = 0.87F, Fat = 0.15F, Gram = 43, FoodCategoryId = 11 };
            Food pazi = new Food() { Name = "Pazı", Calorie = 7, Carbonhidrate = 1.35F, Protein = 0.65F, Fat = 0.07F, Gram = 36, FoodCategoryId = 11 };
            Food kabak = new Food() { Name = "Kabak", Calorie = 33, Carbonhidrate = 6.10F, Protein = 2.37F, Fat = 0.63F, Gram = 196, FoodCategoryId = 11 };
            Food roka = new Food() { Name = "Roka", Calorie = 5, Carbonhidrate = 0.73F, Protein = 0.52F, Fat = 0.13F, Gram = 20, FoodCategoryId = 11 };
            Food ispanakYemeği = new Food() { Name = "Ispanak Yemeği (Etsiz)", Gram = 100, Calorie = 115, Carbonhidrate = 5.09F, Protein = 2.11F, Fat = 10.3F, FoodCategoryId = 11 };
            Food zeytinFatliSemizotu = new Food() { Name = "Zeytinyağlı Semizotu", Gram = 100, Calorie = 112, Carbonhidrate = 4.98F, Protein = 1.29F, Fat = 10.26F, FoodCategoryId = 11 };
            Food zeytinyağliPazi = new Food() { Name = "Zeytinyağlı Pazı", Gram = 100, Calorie = 131, Carbonhidrate = 11.89F, Protein = 3.74F, Fat = 7.18F, FoodCategoryId = 11 };
            Food zeytinyağliTazeFasulye = new Food() { Name = "Zeytinyağlı Taze Fasülye", Gram = 100, Calorie = 151, Carbonhidrate = 21.39F, Protein = 5.54F, Fat = 5.51F, FoodCategoryId = 11 };
            Food zeytinyağliPirasa = new Food() { Name = "Zeytinyağlı Pırasa", Gram = 100, Calorie = 120, Carbonhidrate = 7.25F, Protein = 0.91F, Fat = 10.27F, FoodCategoryId = 11 };
            Food bezelyeYemeği = new Food() { Name = "Bezelye Yemeği (Etsiz)", Gram = 100, Calorie = 147, Carbonhidrate = 11.07F, Protein = 3.48F, Fat = 10.38F, FoodCategoryId = 11 };
            Food zeytinyağliBrokoli = new Food() { Name = "Zeytinyağlı Brokoli", Gram = 100, Calorie = 80, Carbonhidrate = 7.14F, Protein = 2.37F, Fat = 5.41F, FoodCategoryId = 11 };
            Food karnabaharYemegi = new Food() { Name = "Karnabahar Yemeği(Etsiz)", Gram = 100, Calorie = 115, Carbonhidrate = 5.29F, Protein = 1.48F, Fat = 10.41F, FoodCategoryId = 11 };
            Food bamyaYemegi = new Food() { Name = "Bamya Yemeği (Etsiz)", Gram = 100, Calorie = 113, Carbonhidrate = 4.68F, Protein = 1.06F, Fat = 10.57F, FoodCategoryId = 11 };
            Food zeytinyağliTurlu = new Food() { Name = "Zeytinyağlı Türlü", Gram = 100, Calorie = 112, Carbonhidrate = 8.68F, Protein = 1.33F, Fat = 8.87F, FoodCategoryId = 11 };
            Food zeytinyağliBakla = new Food() { Name = "Zeytinyağlı Bakla", Gram = 100, Calorie = 145, Carbonhidrate = 9.76F, Protein = 3.32F, Fat = 10.69F, FoodCategoryId = 11 };
            Food zeytinyağliKereviz = new Food() { Name = "Zeytinyağlı Kereviz", Gram = 100, Calorie = 90, Carbonhidrate = 7.14F, Protein = 1.92F, Fat = 6.37F, FoodCategoryId = 11 };
            Food zeytinyağliEnginar = new Food() { Name = "Zeytinyağlı Enginar", Gram = 100, Calorie = 146, Carbonhidrate = 12.09F, Protein = 2.93F, Fat = 10.71F, FoodCategoryId = 11 };
            Food sebzeSote = new Food() { Name = "Sebze Sote", Gram = 200, Calorie = 90, Carbonhidrate = 4.55F, Protein = 0.94F, Fat = 10.19F, FoodCategoryId = 11 };
            Food zeytinyağliSebzeDolmasi = new Food() { Name = "Zeytinyağlı Sebze Dolması", Gram = 200, Calorie = 258, Carbonhidrate = 13.59F, Protein = 5.6F, Fat = 13.6F, FoodCategoryId = 11 };
            Food zeytinyağliYaprakSarma = new Food() { Name = "Zeytinyağlı Yaprak Sarma", Gram = 60, Calorie = 108, Carbonhidrate = 8.32F, Protein = 1.33F, Fat = 8.15F, FoodCategoryId = 11 };
            Food zeytinyağliKabak = new Food() { Name = "Zeytinyağlı Kabak", Gram = 100, Calorie = 111, Carbonhidrate = 5.19F, Protein = 0.81F, Fat = 10.18F, FoodCategoryId = 11 };
            Food sadeSalata = new Food() { Name = "Sade Salata (Karışık Yeşillik)", Gram = 55, Calorie = 9, Carbonhidrate = 1.76F, Protein = 0.84F, Fat = 0.13F, FoodCategoryId = 12 };
            Food mercimekliPeynirliSalata = new Food() { Name = "Mercimekli Lor Peynirli Salata", Gram = 255, Calorie = 180, Carbonhidrate = 28, Protein = 2.7F, Fat = 5.1F, FoodCategoryId = 12 };
            Food tavukluSalata = new Food() { Name = "Tavuklu Salata", Gram = 255, Calorie = 225, Carbonhidrate = 5.28F, Protein = 31.38F, Fat = 8.29F, FoodCategoryId = 12 };
            Food etliSalata = new Food() { Name = "Etli Salata (bonfileli/köfteli/fümeli)", Gram = 260, Calorie = 267, Carbonhidrate = 5.28F, Protein = 24.84F, Fat = 16.49F, FoodCategoryId = 12 };
            Food tonBalikliSalata = new Food() { Name = "Ton Balıklı Salata", Gram = 270, Calorie = 215, Carbonhidrate = 5.28F, Protein = 21.96F, Fat = 6.35F, FoodCategoryId = 12 };
            Food kisir = new Food() { Name = "Kısır", Gram = 60, Calorie = 108, Carbonhidrate = 15.84F, Protein = 2.71F, Fat = 4.64F, FoodCategoryId = 11 };
            Food mercimekKoftesi = new Food() { Name = "Mercimet Köftesi", Gram = 30, Calorie = 70, Carbonhidrate = 9.95F, Protein = 2.75F, Fat = 2.41F, FoodCategoryId = 12 };
            Food tabuleSalatasi = new Food() { Name = "Tabule Salatası", Gram = 370, Calorie = 588, Carbonhidrate = 51, Protein = 14.4F, Fat = 33.3F, FoodCategoryId = 12 };
            Food peynirliYumurtaliSalata = new Food() { Name = "Peynirli Yumurtalı Salata", Gram = 260, Calorie = 225, Carbonhidrate = 6.7F, Protein = 16.78F, Fat = 9.81F, FoodCategoryId = 12 };
            Food cobanSalata = new Food() { Name = "Çoban Salata", Gram = 220, Calorie = 115, Carbonhidrate = 16.62F, Protein = 3.19F, Fat = 3.76F, FoodCategoryId = 12 };
            Food gavurdağiSalata = new Food() { Name = "Gavurdağı Salata", Gram = 155, Calorie = 114, Carbonhidrate = 7.71F, Protein = 2.95F, Fat = 7.72F, FoodCategoryId = 12 };
            Food patatesSalatasi = new Food() { Name = "Patates Salatası", Gram = 187, Calorie = 132, Carbonhidrate = 21.77F, Protein = 2.46F, Fat = 3.33F, FoodCategoryId = 12 };
            Food meyveSalatasi = new Food() { Name = "Meyve Salatası", Gram = 315, Calorie = 172, Carbonhidrate = 38.4F, Protein = 1.65F, Fat = 0.96F, FoodCategoryId = 12 };
            Food kestane = new Food() { Name = "Kestane", Gram = 50, Calorie = 98, Carbonhidrate = 22.09F, Protein = 0.81F, Fat = 0.62F, FoodCategoryId = 10 };
            Food patlamişMisir = new Food() { Name = "Patlamış Mısır", Gram = 20, Calorie = 76, Carbonhidrate = 15.58F, Protein = 2.40F, Fat = 0.84F, FoodCategoryId = 10 };
            Food sariLeblebi = new Food() { Name = "Sarı Leblebi", Gram = 20, Calorie = 71, Carbonhidrate = 11.7F, Protein = 3.73F, Fat = 1.25F, FoodCategoryId = 13 };
            Food beyazLeblebi = new Food() { Name = "Beyaz Leblebi", Gram = 20, Calorie = 72, Carbonhidrate = 11.9F, Protein = 3.79F, Fat = 1.2F, FoodCategoryId = 13 };
            Food findik = new Food() { Name = "Fındık", Gram = 15, Calorie = 97, Carbonhidrate = 2.57F, Protein = 2.30F, Fat = 9.36F, FoodCategoryId = 13 };
            Food badem = new Food() { Name = "Sarı Leblebi", Gram = 17, Calorie = 97, Carbonhidrate = 3.62F, Protein = 3.55F, Fat = 8.39F, FoodCategoryId = 13 };
            Food yerFistigi = new Food() { Name = "Yer Fıstığı", Gram = 30, Calorie = 170, Carbonhidrate = 4.84F, Protein = 7.74F, Fat = 14.77F, FoodCategoryId = 13 };
            Food antepFistigi = new Food() { Name = "Antep Fıstığı", Gram = 18, Calorie = 103, Carbonhidrate = 5.09F, Protein = 3.79F, Fat = 8.25F, FoodCategoryId = 13 };
            Food ceviz = new Food() { Name = "Ceviz", Gram = 10, Calorie = 52, Carbonhidrate = 1.1F, Protein = 1.22F, Fat = 5.22F, FoodCategoryId = 13 };
            Food kabakCekirdegi = new Food() { Name = "Kabak Çekirdeği", Gram = 20, Calorie = 104.4F, Carbonhidrate = 2.68F, Protein = 6.6F, Fat = 8.42F, FoodCategoryId = 13 };
            Food cigKaju = new Food() { Name = "Çiğ Kaju", Gram = 20, Calorie = 111, Carbonhidrate = 6.04F, Protein = 3.64F, Fat = 8.77F, FoodCategoryId = 13 };
            Food kavrulmusKaju = new Food() { Name = "Kaju Fıstığı Kavrulmuş", Gram = 40, Calorie = 230, Carbonhidrate = 13.08F, Protein = 6.12F, Fat = 18.54F, FoodCategoryId = 13 };
            Food galeta = new Food() { Name = "Sarı Leblebi", Gram = 7, Calorie = 32, Carbonhidrate = 5.2F, Protein = 0.66F, Fat = 0.76F, FoodCategoryId = 13 };
            Food erikKurusu = new Food() { Name = "Erik Kurusu", Gram = 100, Calorie = 267, Carbonhidrate = 68.9F, Protein = 3.5F, Fat = 1.2F, FoodCategoryId = 13 };
            Food uzumKurusu = new Food() { Name = "Üzüm Kurusu", Gram = 100, Calorie = 277, Carbonhidrate = 71.2F, Protein = 2.3F, Fat = 0.5F, FoodCategoryId = 13 };
            Food kayisiKurusu = new Food() { Name = "Kayısı Kurusu", Gram = 100, Calorie = 284, Carbonhidrate = 72.2F, Protein = 5.4F, Fat = 1.2F, FoodCategoryId = 13 };
            Food elmaKurusu = new Food() { Name = "Elma Kurusu", Gram = 100, Calorie = 238, Carbonhidrate = 62.3F, Protein = 2.1F, Fat = 2.1F, FoodCategoryId = 13 };
            Food muzKurusu = new Food() { Name = "Muz Kurusu", Gram = 100, Calorie = 390, Carbonhidrate = 80.5F, Protein = 3.9F, Fat = 1.8F, FoodCategoryId = 13 };
            Food kuruIncır = new Food() { Name = "Kuru İncir", Gram = 100, Calorie = 290, Carbonhidrate = 78, Protein = 3.6F, Fat = 1.2F, FoodCategoryId = 13 };
            Food hurma = new Food() { Name = "Hurma", Gram = 100, Calorie = 277, Carbonhidrate = 74, Protein = 2, Fat = 0.4F, FoodCategoryId = 13 };
            Food yabanMersini = new Food() { Name = "Yaban Mersini Kurusu", Gram = 100, Calorie = 48, Carbonhidrate = 12, Protein = 0.38F, Fat = 0.38F, FoodCategoryId = 3 };
            Food armutKurusu = new Food() { Name = "Armut Kurusu", Gram = 100, Calorie = 270, Carbonhidrate = 62.6F, Protein = 2.3F, Fat = 0.6F, FoodCategoryId = 13 };
            Food patatesCipsi = new Food() { Name = "Patates Cipsi", Gram = 100, Calorie = 719, Carbonhidrate = 10.46F, Protein = 1.23F, Fat = 74.78F, FoodCategoryId = 10 };
            Food misirCipsi = new Food() { Name = "Mısır Cipsi", Gram = 100, Calorie = 404, Carbonhidrate = 42.68F, Protein = 4.95F, Fat = 25.05F, FoodCategoryId = 10 };
            Food pringles = new Food() { Name = "Pringles Original", Gram = 165, Calorie = 861, Carbonhidrate = 84.15F, Protein = 6.27F, Fat = 56.1F, FoodCategoryId = 10 };
            Food ulkerGofret = new Food() { Name = "Ülker Çikolatalı Gofret", Gram = 100, Calorie = 198, Carbonhidrate = 20.72F, Protein = 2.13F, Fat = 11.83F, FoodCategoryId = 10 };
            Food jelibon = new Food() { Name = "Jelibon", Gram = 100, Calorie = 302, Carbonhidrate = 68.31F, Protein = 5.85F, Fat = 0.09F, FoodCategoryId = 10 };
            Food petiborBiskuvi = new Food() { Name = "Petibör Bisküvi", Gram = 175, Calorie = 765, Carbonhidrate = 139.77F, Protein = 13.53F, Fat = 16.8F, FoodCategoryId = 10 };
            Food formKepekliBiskuvi = new Food() { Name = "Form Kepekli Bisküvi", Gram = 45, Calorie = 184, Carbonhidrate = 26.69F, Protein = 5.9F, Fat = 4.86F, FoodCategoryId = 10 };
            Food ciciBebeBiskuvi = new Food() { Name = "Cicibebe Bisküvi", Gram = 4, Calorie = 18, Carbonhidrate = 2.96F, Protein = 0.18F, Fat = 0.6F, FoodCategoryId = 10 };
            Food cikolata = new Food() { Name = "Çikolata", Gram = 5, Calorie = 26, Carbonhidrate = 2.9F, Protein = 0.22F, Fat = 1.76F, FoodCategoryId = 10 };
            Food proteinBar = new Food() { Name = "Protein Bar", Gram = 50, Calorie = 76, Carbonhidrate = 6.6F, Protein = 2.21F, Fat = 4.54F, FoodCategoryId = 10 };
            Food oreo = new Food() { Name = "Oreo", Gram = 57, Calorie = 270, Carbonhidrate = 41.04F, Protein = 2, Fat = 10.83F, FoodCategoryId = 10 };
            Food olips = new Food() { Name = "Olips Şeker", Gram = 76, Calorie = 286, Carbonhidrate = 72.2F, Protein = 0, Fat = 0, FoodCategoryId = 10 };
            Food tadelle = new Food() { Name = "Tadelle Çikolata", Gram = 30, Calorie = 167, Carbonhidrate = 14.31F, Protein = 2.7F, Fat = 10.98F, FoodCategoryId = 10 };
            Food dido = new Food() { Name = "Dido Çikolata", Gram = 35, Calorie = 190, Carbonhidrate = 21.88F, Protein = 2.7F, Fat = 9.98F, FoodCategoryId = 10 };
            Food karamGurme = new Food() { Name = "Karam Gurme", Gram = 50, Calorie = 259, Carbonhidrate = 29, Protein = 2.75F, Fat = 14, FoodCategoryId = 10 };
            Food etiBrownie = new Food() { Name = "Eti Brownie Gold", Gram = 40, Calorie = 154, Carbonhidrate = 22, Protein = 2.04F, Fat = 7.92F, FoodCategoryId = 10 };
            Food kinderSutDilimi = new Food() { Name = "Kinder Süt Dilimi", Gram = 28, Calorie = 118, Carbonhidrate = 10.75F, Protein = 2.16F, Fat = 7.28F, FoodCategoryId = 10 };
            Food kinderSurpriz = new Food() { Name = "Kinder Sürpriz Yumurta", Gram = 20, Calorie = 110, Carbonhidrate = 10.4F, Protein = 1.6F, Fat = 6.8F, FoodCategoryId = 10 };
            Food etiGong = new Food() { Name = "Eti Gong", Gram = 11, Calorie = 50, Carbonhidrate = 7.84F, Protein = 0.64F, Fat = 1.78F, FoodCategoryId = 10 };
            Food biskrem = new Food() { Name = "Biskrem", Gram = 10, Calorie = 50, Carbonhidrate = 6.51F, Protein = 0.45F, Fat = 2.41F, FoodCategoryId = 10 };
            Food probis = new Food() { Name = "Ülker Probis", Gram = 8, Calorie = 39, Carbonhidrate = 4.37F, Protein = 0.93F, Fat = 1.9F, FoodCategoryId = 10 };
            Food sutBurger = new Food() { Name = "Süt Burger", Gram = 35, Calorie = 113, Carbonhidrate = 17.05F, Protein = 1.75F, Fat = 3.78F, FoodCategoryId = 10 };
            Food dankek = new Food() { Name = "Dankek 8kek", Gram = 55, Calorie = 90, Carbonhidrate = 12.65F, Protein = 0.88F, Fat = 4.01F, FoodCategoryId = 10 };
            Food brownieIntense = new Food() { Name = "Brownie Intense", Gram = 50, Calorie = 232, Carbonhidrate = 26.5F, Protein = 2.3F, Fat = 12.85F, FoodCategoryId = 10 };
            Food etiTopkek1 = new Food() { Name = "Eti Topkek Kakolu", Gram = 40, Calorie = 167, Carbonhidrate = 22.96F, Protein = 2.12F, Fat = 7.24F, FoodCategoryId = 10 };
            Food etiPopkek2 = new Food() { Name = "Eti Popkek Meyveli", Gram = 60, Calorie = 264, Carbonhidrate = 34.62F, Protein = 2.82F, Fat = 12.6F, FoodCategoryId = 10 };
            Food etiTopKek3 = new Food() { Name = "Eti Topkek Portakallı", Gram = 40, Calorie = 167, Carbonhidrate = 22.96F, Protein = 2.12F, Fat = 7.24F, FoodCategoryId = 10 };
            Food halley = new Food() { Name = "Halley", Gram = 30, Calorie = 132, Carbonhidrate = 20.31F, Protein = 1.2F, Fat = 5.1F, FoodCategoryId = 1 };
            Food kremaliBiskuvi = new Food() { Name = "Ülker Kremalı Bisküvi", Gram = 7, Calorie = 33, Carbonhidrate = 5.16F, Protein = 0.36F, Fat = 1.27F, FoodCategoryId = 10 };
            Food cokoprens = new Food() { Name = "Ülker Çokoprens", Gram = 30, Calorie = 152, Carbonhidrate = 18.6F, Protein = 1.68F, Fat = 7.8F, FoodCategoryId = 10 };
            Food etiCin = new Food() { Name = "Eti Cin", Gram = 10, Calorie = 44, Carbonhidrate = 7.43F, Protein = 0.47F, Fat = 1.38F, FoodCategoryId = 10 };
            Food etiNero = new Food() { Name = "Eti Nero", Gram = 120, Calorie = 584, Carbonhidrate = 69.72F, Protein = 8.28F, Fat = 29.28F, FoodCategoryId = 10 };
            Food etiTutku = new Food() { Name = "Eti Tutku", Gram = 10, Calorie = 51, Carbonhidrate = 6.1F, Protein = 0.5F, Fat = 2.6F, FoodCategoryId = 10 };
            Food etiBenimO = new Food() { Name = "Eti Benim'O", Gram = 10, Calorie = 46, Carbonhidrate = 6.13F, Protein = 0.47F, Fat = 2.16F, FoodCategoryId = 10 };
            Food etiBurcak = new Food() { Name = "Eti Burçak", Gram = 15, Calorie = 68, Carbonhidrate = 9.87F, Protein = 0.93F, Fat = 2.54F, FoodCategoryId = 10 };
            Food ulkerIkram = new Food() { Name = "Ülker İkram", Gram = 84, Calorie = 405, Carbonhidrate = 52.92F, Protein = 6.47F, Fat = 17.64F, FoodCategoryId = 10 };
            Food lotus = new Food() { Name = "Lotus Bisküvi", Gram = 125, Calorie = 605, Carbonhidrate = 90.75F, Protein = 6.13F, Fat = 23.75F, FoodCategoryId = 10 };
            Food gretaZeytinli = new Food() { Name = "Şölen Greta Zeytinli", Gram = 30, Calorie = 133, Carbonhidrate = 18.1F, Protein = 2.8F, Fat = 5.4F, FoodCategoryId = 10 };
            Food cokonat = new Food() { Name = "Ülker Çokonat", Gram = 33, Calorie = 181, Carbonhidrate = 19.11F, Protein = 2.05F, Fat = 11.32F, FoodCategoryId = 10 };
            Food kinderBueno = new Food() { Name = "Kinder Bueno", Gram = 21, Calorie = 120, Carbonhidrate = 10.4F, Protein = 1.81F, Fat = 7.83F, FoodCategoryId = 10 };
            Food etiHoşbeş = new Food() { Name = "Eti Hoşbeş", Gram = 40, Calorie = 197, Carbonhidrate = 25.56F, Protein = 3.04F, Fat = 9.8F, FoodCategoryId = 10 };
            Food twix = new Food() { Name = "Twix", Gram = 50, Calorie = 250, Carbonhidrate = 34, Protein = 4, Fat = 12, FoodCategoryId = 10 };
            Food snickers = new Food() { Name = "Snickers", Gram = 50, Calorie = 237, Carbonhidrate = 31.31F, Protein = 3.8F, Fat = 11.35F, FoodCategoryId = 10 };
            Food mars = new Food() { Name = "Mars", Gram = 50, Calorie = 225, Carbonhidrate = 35, Protein = 2, Fat = 8.5F, FoodCategoryId = 10 };
            Food albeni = new Food() { Name = "Ülker Albeni", Gram = 40, Calorie = 206, Carbonhidrate = 25.2F, Protein = 2.24F, Fat = 10.64F, FoodCategoryId = 10 };
            Food crunch = new Food() { Name = "Crunch Çikolata", Gram = 33, Calorie = 169, Carbonhidrate = 20.16F, Protein = 2.05F, Fat = 8.74F, FoodCategoryId = 10 };
            Food metro = new Food() { Name = "Ülker Metro", Gram = 40, Calorie = 184, Carbonhidrate = 27.36F, Protein = 1.96F, Fat = 7.4F, FoodCategoryId = 10 };
            Food frigo = new Food() { Name = "Alaska Frigo", Gram = 60, Calorie = 193, Carbonhidrate = 22.98F, Protein = 2.4F, Fat = 9.78F, FoodCategoryId = 10 };
            Food cocoStar = new Food() { Name = "Coco Star", Gram = 28, Calorie = 148, Carbonhidrate = 15.48F, Protein = 1.2F, Fat = 0, FoodCategoryId = 10 };
            Food cubukKraker = new Food() { Name = "Sade Çubuk Kraker", Gram = 52, Calorie = 200, Carbonhidrate = 40.82F, Protein = 5.51F, Fat = 2.91F, FoodCategoryId = 10 };
            Food susamliCubukKraker = new Food() { Name = "Susamlı Çubuk Kraker", Gram = 37, Calorie = 172, Carbonhidrate = 22.39F, Protein = 3.89F, Fat = 7.1F, FoodCategoryId = 10 };
            Food cizi = new Food() { Name = "Çizi Bisküvi", Gram = 20, Calorie = 113, Carbonhidrate = 5.47F, Protein = 3.15F, Fat = 8.86F, FoodCategoryId = 10 };
            Food cornetto = new Food() { Name = "Cornetto", Gram = 75, Calorie = 125, Carbonhidrate = 15, Protein = 1.56F, Fat = 6.25F, FoodCategoryId = 10 };
            Food magnum = new Food() { Name = "Magnum", Gram = 77, Calorie = 239, Carbonhidrate = 24.64F, Protein = 2.7F, Fat = 14.63F, FoodCategoryId = 10 };
            Food misirGevregi = new Food() { Name = "Mısır Gevreği / Cornflakes", Gram = 50, Calorie = 179, Carbonhidrate = 42.05F, Protein = 3.75F, Fat = 0.2F, FoodCategoryId = 10 };
            Food yulafEzmesi = new Food() { Name = "Yulaf Ezmesi", Gram = 100, Calorie = 195, Carbonhidrate = 33.14F, Protein = 8.45F, Fat = 3.45F, FoodCategoryId = 10 };
            Food pilavUstuFasulye = new Food() { Name = "Pilav Üstü Kuru", Gram = 230, Calorie = 336, Carbonhidrate = 57.52F, Protein = 15.28F, Fat = 4.44F, FoodCategoryId = 8 };
            Food hamsiliPilav = new Food() { Name = "Hamsili Pilav", Gram = 230, Calorie = 334, Carbonhidrate = 30.3F, Protein = 26.52F, Fat = 12.29F, FoodCategoryId = 8 };
            Food sehriyeliPilav = new Food() { Name = "Şehriyeli Pilav", Gram = 270, Calorie = 462, Carbonhidrate = 82.85F, Protein = 8.53F, Fat = 10.01F, FoodCategoryId = 8 };
            Food nohutluPilav = new Food() { Name = "Nohutlu Pilav ", Gram = 100, Calorie = 169, Carbonhidrate = 31.29F, Protein = 4.15F, Fat = 2.94F, FoodCategoryId = 8 };
            Food icPilav = new Food() { Name = "İç Pilav", Gram = 100, Calorie = 139, Carbonhidrate = 25.99F, Protein = 2.59F, Fat = 2.53F, FoodCategoryId = 8 };
            Food sadePilav = new Food() { Name = "Sade Pilav", Gram = 80, Calorie = 118, Carbonhidrate = 22.62F, Protein = 1.99F, Fat = 1.99F, FoodCategoryId = 8 };
            Food domatesliBulgurPilavi = new Food() { Name = "Domatesli Bulgur Pilavı", Gram = 230, Calorie = 169, Carbonhidrate = 31.13F, Protein = 4.56F, Fat = 2.61F, FoodCategoryId = 8 };
            Food acemPilavi = new Food() { Name = "Acem Pilavı", Gram = 245, Calorie = 480, Carbonhidrate = 43.69F, Protein = 22.32F, Fat = 23.76F, FoodCategoryId = 8 };
            Food ozbekPilavi = new Food() { Name = "Özbek Pilavı", Gram = 340, Calorie = 570, Carbonhidrate = 58.2F, Protein = 22.35F, Fat = 27.56F, FoodCategoryId = 8 };
            Food basmatiPilavi = new Food() { Name = "Basmati Pilavı", Gram = 50, Calorie = 118, Carbonhidrate = 14.05F, Protein = 1.65F, Fat = 3.1F, FoodCategoryId = 8 };
            Food kuskusPilavi = new Food() { Name = "Kuskus Pilavı", Gram = 180, Calorie = 380, Carbonhidrate = 72.76F, Protein = 11.79F, Fat = 3.75F, FoodCategoryId = 8 };
            Food tereFatlıPrincPilavi = new Food() { Name = "Tereyağlı Pirinç Pilavı", Gram = 170, Calorie = 283, Carbonhidrate = 46.47F, Protein = 4.14F, Fat = 8.65F, FoodCategoryId = 8 };
            Food bezelyeCorbasi = new Food() { Name = "Bezelye Çorbası", Calorie = 31, Carbonhidrate = 3.06F, Protein = 1.05F, Fat = 1.6F, Gram = 150, FoodCategoryId = 14 };
            Food domatesCorbasi = new Food() { Name = "Domates Çorbası", Calorie = 47, Carbonhidrate = 6.53F, Protein = 1.36F, Fat = 1.66F, Gram = 150, FoodCategoryId = 14 };
            Food kasarliDomatesCorbasi = new Food() { Name = "Kaşarlı Domates Çorbası", Calorie = 31, Carbonhidrate = 2.07F, Protein = 1.68F, Fat = 1.73F, Gram = 100, FoodCategoryId = 14 };
            Food ezogelinCorbasi = new Food() { Name = "Ezogelin Çorbası", Calorie = 68, Carbonhidrate = 8.92F, Protein = 2.83F, Fat = 1.76F, Gram = 150, FoodCategoryId = 14 };
            Food iskembeCorbasi = new Food() { Name = "İşkembe Çorbası", Calorie = 139, Carbonhidrate = 4.93F, Protein = 15.14F, Fat = 6.35F, Gram = 100, FoodCategoryId = 14 };
            Food kirmiziMercimekCorbasi = new Food() { Name = "Kırmızı Mercimek Çorbası", Calorie = 68, Carbonhidrate = 12.42F, Protein = 3.69F, Fat = 0.29F, Gram = 150, FoodCategoryId = 14 };
            Food yesilMercimekCorbasi = new Food() { Name = "Yeşil Mercimek Çorbası", Calorie = 121, Carbonhidrate = 12.04F, Protein = 4.5F, Fat = 6.03F, Gram = 150, FoodCategoryId = 14 };
            Food sebzeCorbasi = new Food() { Name = "Sebze Çorbası", Calorie = 44, Carbonhidrate = 6.06F, Protein = 1, Fat = 1.68F, Gram = 100, FoodCategoryId = 14 };
            Food tarhanaCorbasi = new Food() { Name = "Tarhana Çorbası", Calorie = 91, Carbonhidrate = 7.48F, Protein = 3.45F, Fat = 4.93F, Gram = 150, FoodCategoryId = 14 };
            Food yaylaCorbasi = new Food() { Name = "Yayla Çorbası", Calorie = 70, Carbonhidrate = 9.71F, Protein = 12.19F, Fat = 2.41F, Gram = 150, FoodCategoryId = 14 };
            Food tavukCorbasi = new Food() { Name = "Tavuk Çorbası", Calorie = 83, Carbonhidrate = 5.17F, Protein = 5.96F, Fat = 2.95F, Gram = 150, FoodCategoryId = 14 };
            Food balkabagiCorbasi = new Food() { Name = "Balkabaği Çorbası", Calorie = 29, Carbonhidrate = 2.41F, Protein = 1.87F, Fat = 1.19F, Gram = 100, FoodCategoryId = 14 };
            Food mantarCorbasi = new Food() { Name = "Mantar Çorbası", Calorie = 99, Carbonhidrate = 7.36F, Protein = 3.06F, Fat = 6.37F, Gram = 150, FoodCategoryId = 14 };
            Food kremaliMantarCorbasi = new Food() { Name = "Kremalı Mantar Çorbası", Calorie = 120, Carbonhidrate = 5.21F, Protein = 1.92F, Fat = 11.27F, Gram = 150, FoodCategoryId = 14 };
            Food brokoliCorbasi = new Food() { Name = "Brokoli Çorbası", Calorie = 39, Carbonhidrate = 5.06F, Protein = 1.37F, Fat = 1.47F, Gram = 150, FoodCategoryId = 14 };
            Food pacaCorbasi = new Food() { Name = "Paça Çorbası", Calorie = 117, Carbonhidrate = 0.86F, Protein = 18.81F, Fat = 4.29F, Gram = 150, FoodCategoryId = 14 };
            Food balikCorbasi = new Food() { Name = "Balik Çorbası", Calorie = 49, Carbonhidrate = 4.43F, Protein = 4.51F, Fat = 1.27F, Gram = 100, FoodCategoryId = 14 };
            Food tutmacCorbasi = new Food() { Name = "Tutmac Çorbası", Calorie = 72, Carbonhidrate = 7.2F, Protein = 3.01F, Fat = 3.07F, Gram = 100, FoodCategoryId = 14 };
            Food kerevizCorbasi = new Food() { Name = "Kereviz Çorbası", Calorie = 67, Carbonhidrate = 6.51F, Protein = 0.87F, Fat = 4.16F, Gram = 150, FoodCategoryId = 14 };
            Food beyazEkmek = new Food() { Name = "Beyaz Ekmek", Calorie = 71, Carbonhidrate = 13.17F, Protein = 3.2F, Fat = 0.65F, Gram = 30, FoodCategoryId = 1 };
            Food tamBugdayekmeği = new Food() { Name = "Tam Buğday Ekmeği", Calorie = 63, Carbonhidrate = 10.68F, Protein = 3.11F, Fat = 0.88F, Gram = 25, FoodCategoryId = 8 };
            Food cavdarEkmegi = new Food() { Name = "Cavdar Ekmeği", Calorie = 63, Carbonhidrate = 13.15F, Protein = 1.81F, Fat = 0.27F, Gram = 30, FoodCategoryId = 8 };
            Food kepekliEkmegi = new Food() { Name = "Kepekli Ekmek", Calorie = 54, Carbonhidrate = 11.14F, Protein = 1.51F, Fat = 0.38F, Gram = 25, FoodCategoryId = 8 };
            Food grisini = new Food() { Name = "Grissini", Calorie = 20, Carbonhidrate = 3.53F, Protein = 0.51F, Fat = 0.36F, Gram = 5, FoodCategoryId = 8 };
            Food beyaztostEkmeği = new Food() { Name = "Beyaz Tost Ekmeği", Calorie = 76, Carbonhidrate = 14.31F, Protein = 2.21F, Fat = 1, Gram = 30, FoodCategoryId = 8 };
            Food cokTahilliTostEkmegi = new Food() { Name = "Çok Tahıllı Tost Ekmeği", Calorie = 67, Carbonhidrate = 11.65F, Protein = 3.33F, Fat = 0.79F, Gram = 28, FoodCategoryId = 8 };
            Food sandvicEkmegi = new Food() { Name = "Sandviç Ekmeği", Calorie = 178, Carbonhidrate = 37.21F, Protein = 5.07F, Fat = 1.61F, Gram = 65, FoodCategoryId = 8 };
            Food kepekliSandvicEkmegi = new Food() { Name = "Kepekli Sandviç Ekmeği", Calorie = 171, Carbonhidrate = 31.08F, Protein = 6.72F, Fat = 1.5F, Gram = 70, FoodCategoryId = 8 };
            Food hamburgerEkmeği = new Food() { Name = "Hamburger Ekmeği", Calorie = 142, Carbonhidrate = 29.64F, Protein = 3.64F, Fat = 1.04F, Gram = 52, FoodCategoryId = 8 };
            Food yufka = new Food() { Name = "Yufka", Calorie = 387, Carbonhidrate = 80.18F, Protein = 10.94F, Fat = 1.41F, Gram = 160, FoodCategoryId = 8 };
            Food irmik = new Food() { Name = "İrmik", Calorie = 36, Carbonhidrate = 7.28F, Protein = 1.27F, Fat = 0.11F, Gram = 10, FoodCategoryId = 8 };
            Food misirNisastasi = new Food() { Name = "Mısır Nişastası", Calorie = 37, Carbonhidrate = 9.06F, Protein = 0.02F, Fat = 0.08F, Gram = 10, FoodCategoryId = 8 };
            Food galetaUnu = new Food() { Name = "Galeta Unu", Calorie = 40, Carbonhidrate = 7.2F, Protein = 1.34F, Fat = 0.53F, Gram = 10, FoodCategoryId = 8 };
            Food un = new Food() { Name = "Beyaz Un", Calorie = 40, Carbonhidrate = 8.54F, Protein = 0.04F, Fat = 0.01F, Gram = 10, FoodCategoryId = 8 };
            Food peynirliBorek = new Food() { Name = "Peynirli Börek", Calorie = 194, Carbonhidrate = 25.11F, Protein = 7.58F, Fat = 6.85F, Gram = 75, FoodCategoryId = 8 };
            Food patatesliBorek = new Food() { Name = "Patatesli Börek", Calorie = 204, Carbonhidrate = 26.87F, Protein = 4.27F, Fat = 8.67F, Gram = 75, FoodCategoryId = 8 };
            Food ispanakliBorek = new Food() { Name = "Ispanaklı Börek", Calorie = 116, Carbonhidrate = 21.39F, Protein = 4.29F, Fat = 2.35F, Gram = 75, FoodCategoryId = 8 };
            Food suBoregi = new Food() { Name = "Su Böreği", Calorie = 172, Carbonhidrate = 18.77F, Protein = 5.39F, Fat = 8.24F, Gram = 75, FoodCategoryId = 8 };
            Food cigBorek = new Food() { Name = "Çiğ Börek", Calorie = 264, Carbonhidrate = 32.76F, Protein = 3.18F, Fat = 13.28F, Gram = 70, FoodCategoryId = 8 };
            Food patlicanliBorek = new Food() { Name = "Patlıcanlı Börek", Calorie = 107, Carbonhidrate = 18.43F, Protein = 4.05F, Fat = 1.08F, Gram = 75, FoodCategoryId = 8 };
            Food biskuviliPasta = new Food() { Name = "Bisküvili Pasta", Calorie = 361, Carbonhidrate = 57.1F, Protein = 11.22F, Fat = 7.97F, Gram = 220, FoodCategoryId = 4 };
            Food cikolataliPasta = new Food() { Name = "Çikolatalı Pasta", Calorie = 577, Carbonhidrate = 39.56F, Protein = 7.44F, Fat = 42.85F, Gram = 150, FoodCategoryId = 4 };
            Food meyveliPasta = new Food() { Name = "Meyveli Pasta", Calorie = 257, Carbonhidrate = 41.5F, Protein = 6.38F, Fat = 6.09F, Gram = 150, FoodCategoryId = 4 };
            Food muzluRuloiPasta = new Food() { Name = "Muzlu Rulo Pasta", Calorie = 286, Carbonhidrate = 43.49F, Protein = 10.27F, Fat = 6.8F, Gram = 160, FoodCategoryId = 4 };
            Food sadeKek = new Food() { Name = "Sade Kek", Calorie = 241, Carbonhidrate = 32.95F, Protein = 4.45F, Fat = 9.15F, Gram = 70, FoodCategoryId = 4 };
            Food kakaoluKek = new Food() { Name = "Kakaolu Kek", Calorie = 268, Carbonhidrate = 31.2F, Protein = 3.94F, Fat = 13.11F, Gram = 70, FoodCategoryId = 4 };
            Food havucluKek = new Food() { Name = "Havuclu Kek", Calorie = 249, Carbonhidrate = 26.91F, Protein = 3.84F, Fat = 13.36F, Gram = 70, FoodCategoryId = 4 };
            Food portakalliKek = new Food() { Name = "Portakallı Kek", Calorie = 188, Carbonhidrate = 28.92F, Protein = 3.55F, Fat = 5.7F, Gram = 70, FoodCategoryId = 4 };
            Food elmaliKurabiye = new Food() { Name = "Elmalı Kurabiye", Calorie = 153, Carbonhidrate = 18.08F, Protein = 2.49F, Fat = 7.66F, Gram = 45, FoodCategoryId = 4 };
            Food findikliKurabiye = new Food() { Name = "Fındıklı Kurabiye", Calorie = 238, Carbonhidrate = 22.22F, Protein = 3.86F, Fat = 14.84F, Gram = 45, FoodCategoryId = 4 };
            Food cevizliKurabiye = new Food() { Name = "Cevizli Kurabiye", Calorie = 203, Carbonhidrate = 21.61F, Protein = 3.69F, Fat = 11.38F, Gram = 45, FoodCategoryId = 4 };
            Food cikolataliKurabiye = new Food() { Name = "Çikolatalı Kurabiye", Calorie = 210, Carbonhidrate = 21.95F, Protein = 2.97F, Fat = 12.20F, Gram = 45, FoodCategoryId = 4 };
            Food yulafliFitKurabiye = new Food() { Name = "Yulafli Fit Kurabiye", Calorie = 161, Carbonhidrate = 17.65F, Protein = 5.48F, Fat = 8.68F, Gram = 45, FoodCategoryId = 4 };
            Food kuruUzumluDiyetKurabiye = new Food() { Name = "Kuru Uzumlu Diyet Kurabiye", Calorie = 102, Carbonhidrate = 19.39F, Protein = 3.46F, Fat = 1.54F, Gram = 45, FoodCategoryId = 4 };
            Food tuzluPastaneKurabiyesi = new Food() { Name = "Tuzlu Pastane Kurabiyesi", Calorie = 184, Carbonhidrate = 19.31F, Protein = 3.82F, Fat = 10.22F, Gram = 30, FoodCategoryId = 4 };
            Food unKurabiyesi = new Food() { Name = "Tuzlu Pastane Kurabiyesi", Calorie = 128, Carbonhidrate = 21.06F, Protein = 0.18F, Fat = 4.67F, Gram = 30, FoodCategoryId = 4 };
            Food kandilSimidi = new Food() { Name = "Kandil Simidi", Calorie = 167, Carbonhidrate = 14.97F, Protein = 2.93F, Fat = 60.67F, Gram = 35, FoodCategoryId = 4 };
            Food simit = new Food() { Name = "Simit", Calorie = 275, Carbonhidrate = 57.14F, Protein = 10.71F, Fat = 3.57F, Gram = 100, FoodCategoryId = 1 };
            Food pogaca = new Food() { Name = "Poğaça", Calorie = 243, Carbonhidrate = 22.33F, Protein = 4.91F, Fat = 14.74F, Gram = 70, FoodCategoryId = 1 };
            Food peynirliPogaca = new Food() { Name = "Peynirli Poğaça", Calorie = 274, Carbonhidrate = 21.4F, Protein = 6.1F, Fat = 18.29F, Gram = 70, FoodCategoryId = 8 };
            Food DereotluPogaca = new Food() { Name = "Dereotlu Poğaça", Calorie = 234, Carbonhidrate = 25.2F, Protein = 5.09F, Fat = 20.44F, Gram = 70, FoodCategoryId = 8 };
            Food ZeytinliPogaca = new Food() { Name = "Zeytinli Poğaça", Calorie = 267, Carbonhidrate = 23.97F, Protein = 5.06F, Fat = 17.27F, Gram = 70, FoodCategoryId = 8 };
            Food patatesliPogaca = new Food() { Name = "Patatesli Poğaça", Calorie = 230, Carbonhidrate = 20.01F, Protein = 3.48F, Fat = 14.96F, Gram = 70, FoodCategoryId = 8 };
            Food acma = new Food() { Name = "Acma", Calorie = 341, Carbonhidrate = 35.22F, Protein = 5.91F, Fat = 23.89F, Gram = 90, FoodCategoryId = 1 };
            Food cikolataliAcma = new Food() { Name = "Cikolatalı Acma", Calorie = 268, Carbonhidrate = 36.71F, Protein = 5.32F, Fat = 10.83F, Gram = 75, FoodCategoryId = 8 };
            Food zeytinliAcma = new Food() { Name = "Zeytinli Acma", Calorie = 354, Carbonhidrate = 31.25F, Protein = 5.27F, Fat = 22.95F, Gram = 90, FoodCategoryId = 8 };
            Food kurufasulyeEtsiz = new Food() { Name = "Etsiz Kuru Fasulye", Calorie = 250, Carbonhidrate = 45.16F, Protein = 17.51F, Fat = 0.63F, Gram = 180, FoodCategoryId = 8 };
            Food nohutYemegiEtsiz = new Food() { Name = "Etsiz Kuru Fasulye", Calorie = 322, Carbonhidrate = 41.16F, Protein = 11.80F, Fat = 0.63F, Gram = 200, FoodCategoryId = 8 };
            Food bezelyeYemegi = new Food() { Name = "Bezelye Yemegi    ", Calorie = 132, Carbonhidrate = 22.42F, Protein = 6.15F, Fat = 2.39F, Gram = 200, FoodCategoryId = 8 };
            Food mercimekYemegi = new Food() { Name = "Mercimnek Yemegi ", Calorie = 164, Carbonhidrate = 17.04F, Protein = 8.97F, Fat = 4.52F, Gram = 230, FoodCategoryId = 8 };
            Food zeytinFatlıBarbunya = new Food() { Name = "ZeytinFatlı Barbunya ", Calorie = 140, Carbonhidrate = 42.83F, Protein = 15.99F, Fat = 14.14F, Gram = 140, FoodCategoryId = 8 };
            Food haslanmisMisir = new Food() { Name = "zeytinFatlıBarbunya ", Calorie = 140, Carbonhidrate = 42.83F, Protein = 15.99F, Fat = 14.14F, Gram = 140, FoodCategoryId = 8 };
            Food meksikaFasulyesi = new Food() { Name = "Meksika Fasulyesi ", Calorie = 607, Carbonhidrate = 110.32F, Protein = 40.55F, Fat = 1.91F, Gram = 180, FoodCategoryId = 8 };
            Food soyaFasulyesi = new Food() { Name = "Soya Fasulyesi ", Calorie = 274, Carbonhidrate = 0.31F, Protein = 28.31F, Fat = 17.79F, Gram = 180, FoodCategoryId = 8 };
            Food balikFati = new Food() { Name = "Balik Fati ", Calorie = 44, Carbonhidrate = 0, Protein = 0, Fat = 4.99F, Gram = 5, FoodCategoryId = 5 };
            Food icFati = new Food() { Name = "İç Fati ", Calorie = 135, Carbonhidrate = 0, Protein = 0, Fat = 15F, Gram = 15, FoodCategoryId = 15 };
            Food kuyrukFati = new Food() { Name = "Kuyruk Fati ", Calorie = 79, Carbonhidrate = 0.01F, Protein = 0.29F, Fat = 8.61F, Gram = 14, FoodCategoryId = 15 };
            Food aycicekFati = new Food() { Name = "Aycicek Fati ", Calorie = 44, Carbonhidrate = 0, Protein = 0, Fat = 5, Gram = 5, FoodCategoryId = 15 };
            Food fındıkFatı = new Food() { Name = "Fındık Fati ", Calorie = 35, Carbonhidrate = 0, Protein = 0, Fat = 4, Gram = 4, FoodCategoryId = 15 };
            Food zeytinFatı = new Food() { Name = "Zeytin Fati ", Calorie = 40, Carbonhidrate = 0.01F, Protein = 0, Fat = 4.5F, Gram = 4, FoodCategoryId = 15 };

            context.FoodCategories.Add(denizUrunu);
            context.FoodCategories.Add(tavuk);
            context.FoodCategories.Add(meyve);
            context.FoodCategories.Add(tatli);
            context.FoodCategories.Add(sutVeSutUrunu);
            context.FoodCategories.Add(kirmiziEt);
            context.FoodCategories.Add(kahvaltilik);
            context.FoodCategories.Add(tahil);
            context.FoodCategories.Add(soslar);
            context.FoodCategories.Add(fastfood);
            context.FoodCategories.Add(sebze);
            context.FoodCategories.Add(salatalar);
            context.FoodCategories.Add(cerez);
            context.FoodCategories.Add(corba);
            context.FoodCategories.Add(yag);

            context.Foods.Add(midyeDolma);
            context.Foods.Add(susi);
            context.Foods.Add(KizarmisKanat);
            context.Foods.Add(HaslanmisBut);
            context.Foods.Add(TavukKoftesi);
            context.Foods.Add(TavukluPilav);
            context.Foods.Add(TavukNugget);
            context.Foods.Add(KoriSosluTavuk);
            context.Foods.Add(TavukSote);
            context.Foods.Add(Elma);
            context.Foods.Add(Armut);
            context.Foods.Add(Portakal);
            context.Foods.Add(Greyfurt);
            context.Foods.Add(Ayva);
            context.Foods.Add(Mandalina);
            context.Foods.Add(Kivi);
            context.Foods.Add(Muz);
            context.Foods.Add(Kayisi);
            context.Foods.Add(Cilek);
            context.Foods.Add(TrabzonHurmasi);
            context.Foods.Add(Kiraz);
            context.Foods.Add(Visne);
            context.Foods.Add(Kavun);
            context.Foods.Add(Karpuz);
            context.Foods.Add(Ananas);
            context.Foods.Add(Avakado);
            context.Foods.Add(Mango);
            context.Foods.Add(Ahududu);
            context.Foods.Add(Bogurtlen);
            context.Foods.Add(YesilErik);
            context.Foods.Add(Incir);
            context.Foods.Add(Dut);
            context.Foods.Add(Uzum);
            context.Foods.Add(Nar);
            context.Foods.Add(Seftali);
            context.Foods.Add(Limon);
            context.Foods.Add(KirmiziErik);
            context.Foods.Add(Sutlac);
            context.Foods.Add(Kazandibi);
            context.Foods.Add(Magnolia);
            context.Foods.Add(Tiramisu);
            context.Foods.Add(Cheesecake);
            context.Foods.Add(Gullac);
            context.Foods.Add(TavukGogsuTatli);
            context.Foods.Add(Muhallebi);
            context.Foods.Add(Puding);
            context.Foods.Add(Supangle);
            context.Foods.Add(Trilece);
            context.Foods.Add(Hosmerim);
            context.Foods.Add(Keskul);
            context.Foods.Add(Asure);
            context.Foods.Add(Profiterol);
            context.Foods.Add(MeyveliDondurma);
            context.Foods.Add(SutluDondurma);
            context.Foods.Add(CikolataliDondurma);
            context.Foods.Add(IrmikTatlisi);
            context.Foods.Add(IrmikHelvasi);
            context.Foods.Add(UnHelvasi);
            context.Foods.Add(Baklava);
            context.Foods.Add(Kadayif);
            context.Foods.Add(SogukBaklava);
            context.Foods.Add(Tulumba);
            context.Foods.Add(Kemalpasa);
            context.Foods.Add(HalkaTatlisi);
            context.Foods.Add(SamTatlisi);
            context.Foods.Add(Sobiyet);
            context.Foods.Add(Kunefe);
            context.Foods.Add(Sekerpare);
            context.Foods.Add(Revani);
            context.Foods.Add(LokmaTatlisi);
            context.Foods.Add(Kalburabasti);
            context.Foods.Add(FistikliSarma);
            context.Foods.Add(DilberDudagi);
            context.Foods.Add(SanSebastian);
            context.Foods.Add(BeyazPeynir);
            context.Foods.Add(SuzmePeynir);
            context.Foods.Add(LorPeyniri);
            context.Foods.Add(KasarPeyniri);
            context.Foods.Add(Labne);
            context.Foods.Add(OrguPeynir);
            context.Foods.Add(DilPeyniri);
            context.Foods.Add(HellimPeyniri);
            context.Foods.Add(Mozarella);
            context.Foods.Add(CheddarPeyniri);
            context.Foods.Add(Yogurt);
            context.Foods.Add(Cacik);
            context.Foods.Add(HaslanmisYumurta);
            context.Foods.Add(Omlet);
            context.Foods.Add(PeynirliOmlet);
            context.Foods.Add(MantarliOmlet);
            context.Foods.Add(Menemen);
            context.Foods.Add(SucukluYumurta);
            context.Foods.Add(Kuymak);
            context.Foods.Add(Sucuk);
            context.Foods.Add(Sosis);
            context.Foods.Add(DanaSalam);
            context.Foods.Add(HindiSalam);
            context.Foods.Add(DanaJambon);
            context.Foods.Add(HindiJambon);
            context.Foods.Add(PilicJambon);
            context.Foods.Add(HindiFume);
            context.Foods.Add(PilicFume);
            context.Foods.Add(Pastirma);
            context.Foods.Add(SiyahZeytin);
            context.Foods.Add(YesilZeytin);
            context.Foods.Add(Bal);
            context.Foods.Add(Kaymak);
            context.Foods.Add(TahinHelvasi);
            context.Foods.Add(YazHelvasi);
            context.Foods.Add(Tahin);
            context.Foods.Add(Pekmez);
            context.Foods.Add(Nutella);
            context.Foods.Add(KakaoluFindikKremasi);
            context.Foods.Add(FindikEzmesi);
            context.Foods.Add(FistikEzmesi);
            context.Foods.Add(SekersizFistikEzmesi);
            context.Foods.Add(HaslanmisMakarna);
            context.Foods.Add(DomatesliMakarna);
            context.Foods.Add(SpagettiBolonez);
            context.Foods.Add(PenneArabiata);
            context.Foods.Add(Fettucini);
            context.Foods.Add(Lazanya);
            context.Foods.Add(FirinMakarna);
            context.Foods.Add(MakarnaSalatasi);
            context.Foods.Add(Ketçap);
            context.Foods.Add(Mayonez);
            context.Foods.Add(Hardal);
            context.Foods.Add(BarbekuSos);
            context.Foods.Add(RanchSos);
            context.Foods.Add(BuffaloSos);
            context.Foods.Add(PestoSos);
            context.Foods.Add(NarEkşisi);
            context.Foods.Add(KoriSos);
            context.Foods.Add(SoyaSos);
            context.Foods.Add(CitirTavuk);
            context.Foods.Add(TavukBurger);
            context.Foods.Add(Cheeseburger);
            context.Foods.Add(EtliEkmek);
            context.Foods.Add(Lahmacun);
            context.Foods.Add(Tantuni);
            context.Foods.Add(PizzaKarisik);
            context.Foods.Add(PizzaSebzeli);
            context.Foods.Add(Kokorec);
            context.Foods.Add(Cigkofte);
            context.Foods.Add(DurumTavukDoner);
            context.Foods.Add(DurumEtDoner);
            context.Foods.Add(Kumpir);
            context.Foods.Add(AdanaDurum);
            context.Foods.Add(UrfaDurum);
            context.Foods.Add(PatatesKizartmasi);
            context.Foods.Add(SoganHalkasi);
            context.Foods.Add(KiymaliPide);
            context.Foods.Add(KasarliPide);
            context.Foods.Add(KusbasiPide);
            context.Foods.Add(domates);
            context.Foods.Add(ceriDomates);
            context.Foods.Add(salatalik);
            context.Foods.Add(marul);
            context.Foods.Add(carlistonBiber);
            context.Foods.Add(kirmiziBiber);
            context.Foods.Add(nane);
            context.Foods.Add(feslegen);
            context.Foods.Add(dereotu);
            context.Foods.Add(kisnis);
            context.Foods.Add(biberiye);
            context.Foods.Add(maydanoz);
            context.Foods.Add(turp);
            context.Foods.Add(karnabahar);
            context.Foods.Add(brokoli);
            context.Foods.Add(brukselLahana);
            context.Foods.Add(beyazLahana);
            context.Foods.Add(kirmiziLahana);
            context.Foods.Add(havuc);
            context.Foods.Add(sarimsak);
            context.Foods.Add(sogan);
            context.Foods.Add(yesilSogan);
            context.Foods.Add(semizotu);
            context.Foods.Add(pazi);
            context.Foods.Add(kabak);
            context.Foods.Add(roka);
            context.Foods.Add(ispanakYemeği);
            context.Foods.Add(zeytinFatliSemizotu);
            context.Foods.Add(zeytinyağliPazi);
            context.Foods.Add(zeytinyağliTazeFasulye);
            context.Foods.Add(zeytinyağliPirasa);
            context.Foods.Add(bezelyeYemeği);
            context.Foods.Add(zeytinyağliBrokoli);
            context.Foods.Add(karnabaharYemegi);
            context.Foods.Add(bamyaYemegi);
            context.Foods.Add(zeytinyağliTurlu);
            context.Foods.Add(zeytinyağliBakla);
            context.Foods.Add(zeytinyağliKereviz);
            context.Foods.Add(zeytinyağliEnginar);
            context.Foods.Add(sebzeSote);
            context.Foods.Add(zeytinyağliSebzeDolmasi);
            context.Foods.Add(zeytinyağliYaprakSarma);
            context.Foods.Add(zeytinyağliKabak);
            context.Foods.Add(sadeSalata);
            context.Foods.Add(mercimekliPeynirliSalata);
            context.Foods.Add(tavukluSalata);
            context.Foods.Add(etliSalata);
            context.Foods.Add(tonBalikliSalata);
            context.Foods.Add(kisir);
            context.Foods.Add(mercimekKoftesi);
            context.Foods.Add(tabuleSalatasi);
            context.Foods.Add(peynirliYumurtaliSalata);
            context.Foods.Add(cobanSalata);
            context.Foods.Add(gavurdağiSalata);
            context.Foods.Add(patatesSalatasi);
            context.Foods.Add(meyveSalatasi);
            context.Foods.Add(kestane);
            context.Foods.Add(patlamişMisir);
            context.Foods.Add(sariLeblebi);
            context.Foods.Add(beyazLeblebi);
            context.Foods.Add(findik);
            context.Foods.Add(badem);
            context.Foods.Add(yerFistigi);
            context.Foods.Add(antepFistigi);
            context.Foods.Add(ceviz);
            context.Foods.Add(kabakCekirdegi);
            context.Foods.Add(cigKaju);
            context.Foods.Add(kavrulmusKaju);
            context.Foods.Add(galeta);
            context.Foods.Add(erikKurusu);
            context.Foods.Add(uzumKurusu);
            context.Foods.Add(kayisiKurusu);
            context.Foods.Add(elmaKurusu);
            context.Foods.Add(muzKurusu);
            context.Foods.Add(kuruIncır);
            context.Foods.Add(hurma);
            context.Foods.Add(yabanMersini);
            context.Foods.Add(armutKurusu);
            context.Foods.Add(patatesCipsi);
            context.Foods.Add(misirCipsi);
            context.Foods.Add(pringles);
            context.Foods.Add(ulkerGofret);
            context.Foods.Add(jelibon);
            context.Foods.Add(petiborBiskuvi);
            context.Foods.Add(formKepekliBiskuvi);
            context.Foods.Add(ciciBebeBiskuvi);
            context.Foods.Add(cikolata);
            context.Foods.Add(proteinBar);
            context.Foods.Add(oreo);
            context.Foods.Add(olips);
            context.Foods.Add(tadelle);
            context.Foods.Add(dido);
            context.Foods.Add(karamGurme);
            context.Foods.Add(etiBrownie);
            context.Foods.Add(kinderSutDilimi);
            context.Foods.Add(kinderSurpriz);
            context.Foods.Add(etiGong);
            context.Foods.Add(biskrem);
            context.Foods.Add(probis);
            context.Foods.Add(sutBurger);
            context.Foods.Add(dankek);
            context.Foods.Add(brownieIntense);
            context.Foods.Add(etiTopkek1);
            context.Foods.Add(etiPopkek2);
            context.Foods.Add(etiTopKek3);
            context.Foods.Add(halley);
            context.Foods.Add(kremaliBiskuvi);
            context.Foods.Add(cokoprens);
            context.Foods.Add(etiCin);
            context.Foods.Add(etiNero);
            context.Foods.Add(etiTutku);
            context.Foods.Add(etiBenimO);
            context.Foods.Add(etiBurcak);
            context.Foods.Add(ulkerIkram);
            context.Foods.Add(lotus);
            context.Foods.Add(gretaZeytinli);
            context.Foods.Add(cokonat);
            context.Foods.Add(kinderBueno);
            context.Foods.Add(etiHoşbeş);
            context.Foods.Add(twix);
            context.Foods.Add(snickers);
            context.Foods.Add(mars);
            context.Foods.Add(albeni);
            context.Foods.Add(crunch);
            context.Foods.Add(metro);
            context.Foods.Add(frigo);
            context.Foods.Add(cocoStar);
            context.Foods.Add(cubukKraker);
            context.Foods.Add(susamliCubukKraker);
            context.Foods.Add(cizi);
            context.Foods.Add(cornetto);
            context.Foods.Add(magnum);
            context.Foods.Add(misirGevregi);
            context.Foods.Add(pilavUstuFasulye);
            context.Foods.Add(hamsiliPilav);
            context.Foods.Add(sehriyeliPilav);
            context.Foods.Add(nohutluPilav);
            context.Foods.Add(icPilav);
            context.Foods.Add(sadePilav);
            context.Foods.Add(domatesliBulgurPilavi);
            context.Foods.Add(acemPilavi);
            context.Foods.Add(ozbekPilavi);
            context.Foods.Add(basmatiPilavi);
            context.Foods.Add(kuskusPilavi);
            context.Foods.Add(tereFatlıPrincPilavi);
            context.Foods.Add(bezelyeCorbasi);
            context.Foods.Add(domatesCorbasi);
            context.Foods.Add(kasarliDomatesCorbasi);
            context.Foods.Add(ezogelinCorbasi);
            context.Foods.Add(iskembeCorbasi);
            context.Foods.Add(kirmiziMercimekCorbasi);
            context.Foods.Add(yesilMercimekCorbasi);
            context.Foods.Add(sebzeCorbasi);
            context.Foods.Add(tarhanaCorbasi);
            context.Foods.Add(yaylaCorbasi);
            context.Foods.Add(tavukCorbasi);
            context.Foods.Add(balkabagiCorbasi);
            context.Foods.Add(mantarCorbasi);
            context.Foods.Add(kremaliMantarCorbasi);
            context.Foods.Add(brokoliCorbasi);
            context.Foods.Add(pacaCorbasi);
            context.Foods.Add(balikCorbasi);
            context.Foods.Add(tutmacCorbasi);
            context.Foods.Add(kerevizCorbasi);
            context.Foods.Add(beyazEkmek);
            context.Foods.Add(tamBugdayekmeği);
            context.Foods.Add(cavdarEkmegi);
            context.Foods.Add(kepekliEkmegi);
            context.Foods.Add(grisini);
            context.Foods.Add(beyaztostEkmeği);
            context.Foods.Add(cokTahilliTostEkmegi);
            context.Foods.Add(sandvicEkmegi);
            context.Foods.Add(kepekliSandvicEkmegi);
            context.Foods.Add(hamburgerEkmeği);
            context.Foods.Add(yufka);
            context.Foods.Add(irmik);
            context.Foods.Add(misirNisastasi);
            context.Foods.Add(galetaUnu);
            context.Foods.Add(galetaUnu);
            context.Foods.Add(peynirliBorek);
            context.Foods.Add(patatesliBorek);
            context.Foods.Add(ispanakliBorek);
            context.Foods.Add(suBoregi);
            context.Foods.Add(cigBorek);
            context.Foods.Add(patlicanliBorek);
            context.Foods.Add(biskuviliPasta);
            context.Foods.Add(cikolataliPasta);
            context.Foods.Add(meyveliPasta);
            context.Foods.Add(muzluRuloiPasta);
            context.Foods.Add(sadeKek);
            context.Foods.Add(kakaoluKek);
            context.Foods.Add(havucluKek);
            context.Foods.Add(portakalliKek);
            context.Foods.Add(elmaliKurabiye);
            context.Foods.Add(findikliKurabiye);
            context.Foods.Add(cevizliKurabiye);
            context.Foods.Add(cikolataliKurabiye);
            context.Foods.Add(yulafliFitKurabiye);
            context.Foods.Add(kuruUzumluDiyetKurabiye);
            context.Foods.Add(tuzluPastaneKurabiyesi);
            context.Foods.Add(unKurabiyesi);
            context.Foods.Add(kandilSimidi);
            context.Foods.Add(simit);
            context.Foods.Add(pogaca);
            context.Foods.Add(peynirliPogaca);
            context.Foods.Add(DereotluPogaca);
            context.Foods.Add(ZeytinliPogaca);
            context.Foods.Add(patatesliPogaca);
            context.Foods.Add(acma);
            context.Foods.Add(cikolataliAcma);
            context.Foods.Add(zeytinliAcma);
            context.Foods.Add(kurufasulyeEtsiz);
            context.Foods.Add(nohutYemegiEtsiz);
            context.Foods.Add(bezelyeYemegi);
            context.Foods.Add(mercimekYemegi);
            context.Foods.Add(zeytinFatlıBarbunya);
            context.Foods.Add(haslanmisMisir);
            context.Foods.Add(meksikaFasulyesi);
            context.Foods.Add(soyaFasulyesi);
            context.Foods.Add(balikFati);
            context.Foods.Add(icFati);
            context.Foods.Add(kuyrukFati);
            context.Foods.Add(aycicekFati);
            context.Foods.Add(fındıkFatı);
            context.Foods.Add(zeytinFatı);
            context.SaveChanges();
            Console.WriteLine("Başarılı");

        }
    }
}